# One Page Summary{-}

\begin{itemize}

\item This assessment for `r spp` incorporates a wide range of data sources: landings data and discard estimates; survey indices of abundance, length- and/or age-composition data for each fishery or survey (with conditional age-at-length data used for the surveys); information on weight-at-length, maturity-at-length, and fecundity-at-length; information on natural mortality and the steepness of the Beverton-Holt stock-recruitment relationship; and estimates of ageing error.

\item The longest time series of fishery-independent information off the U.S. west coast arises from the \gls{s-wcgbt} that has been conducted annually from 2003 - 2019. The length and age data from this survey were highly influential on the model estimates of stock size and status. Additionally, these data were used to externally estimate starting parameter values by sex for length-at-age and the fixed values by sex for length-weight relationship.   

\item `r spp` off the U.S. west coast appear to have complex movement patterns, moving across depths, likely driven by season, spawning, and by size. Additionally, observations indicate possible sex-specific aggregations where a higher proportion of female fish are found in shallower (less than 300 m) and deeper waters (greater than 900 m), with higher proportion of males observed at intermediate depths (300 - 700 m).

\item The model parameterization allowed for sex-specific selectivity with female `r spp` never fully selected (maximum selectivity less than 1.0). Large female `r spp` are observed at the deepest depth sampled (1,280 m) off the West Coast and likely extend into unobserved deeper depths. Lack of full selectivity of female `r spp` results in a fraction of unobserved spawning biomass in the population, increasing uncertainty in the estimate of the stock scale that the base model may not fully capture (via asymptotic error assumptions around estimated parameters).  

\item The model was highly sensitive to the assumed value of natural mortality.  The base model fixed the instantaneous rate of natural mortality for females at the median of the prior, 0.108 per year, and estimated male natural mortality as an offset from the female value. When estimated, female natural mortality was well below the median of the prior, at 0.082 per year, which did not appear well supported by longevity information and resulted in estimates of survey catchability at or above 2.0.  However, the relative difference in natural mortality by sex appeared to be well defined across reasonable ranges of natural mortality which informed the decision to only estimate male natural mortality parameterized as an offset from the fixed female value.   

\item The estimated spawning biomass at the beginning of 2021 was `r ssb_2021` mt ($\sim$95 percent asymptotic intervals: `r ssb_2021_low` to `r ssb_2021_hi` mt), which when compared to unfished spawning biomass (`r ssb0` mt) equates to a relative stock status level of `r round(100*depl_2021,0)` percent ($\sim$95 percent asymptotic intervals: `r round(100*depl_2021_low,0)` to `r round(100*depl_2021_hi,0)` percent).  The estimated scale of the stock ($SB_0$) from this assessment, `r ssb0` mt, is lower than the value estimated in the 2011 assessment of 469,866 mt but well within the 2011 $\sim$95 percent asymptotic interval (182,741 - 756,991 mt).

\item  Fishing intensity (1 - SPR) over the past decade has been well below the target $\text{SPR}_{30\%}$, ranging between `r min(spr_recent_10)` and `r max(spr_recent_10)`. The estimated target spawning biomass based on the 25 percent management target is `r format(ssb_targ, big.mark = ',')`. Sustainable total yield, landings plus discards, using $\text{SPR}_{30\%}$ is estimated at `r format(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], digits = 0, scientific = FALSE, big.mark = ",")` mt.   

\end{itemize}

\newpage