# Introduction

The `r spp`, _Microstomus pacificus_ is a flatfish belonging to the family Pleuronectidae and is called a sole although it is a flounder.  `r spp` has also been known by several different common names including slippery sole, lemon sole, smear dab, rubber sole, short finned sole, slime sole, and tongue sole.  Although there was little interest in `r spp` when the U.S. west coast trawl fishery first began, the species is now commonly landed.

This is an assessment of the Dover sole population off of the U.S. West, including coastal waters of California, Oregon, and Washington from the U.S./Mexico border to the U.S./Canadian border (Figure \ref{fig:map}).  It does not include Canadian or Alaskan populations and assumes that these northern populations do not contribute to the stock being assessed here.


## Life History

`r executive[["stock"]]` `r spp` range from Baja California to the Bering Sea and eastern Aleutian Islands [@kramer_guide_1995]. `r spp` are generally found on mud or mud-sand bottom deeper than 20 fathoms (37 m) and out to deeper than 1,500 m [@jacobson_bathymetric_1993]. They feed on polychaete worms, pink shrimp, brittle stars, gammarid amphipods, and small bivalves [@pearcy_feeding_1978; @gabriel_feeding_1981].  `r spp` exhibit dimorphic growth by sex with females off the West Coast reaching a maximum length around 48 cm, approximately 5 cm greater than the males. `r spp` are estimated to live up to a maximum age of approximately 50 years.

Based on samples from the commercial fishery in northern California, Hagerman [-@hagerman_biology_1952] concluded that the spawning period for `r spp` is during November to March or April with heavy spawning during December to February.  In contrast, a later study by Markle et al. [-@markle_metamorphosis_1992] concluded that `r spp` off the coast of Oregon appear to reach peak spawning in early spring. Spawning occurs in relatively deep water [@hagerman_biology_1952] and prior to 1954 few `r spp` were caught during winter months because the fish are generally unavailable on the shelf during winter.  `r spp` eggs and larvae are buoyant [@hagerman_biology_1952] and this species has an extended larval phase lasting at least one year [@pearcy_distribution_1977; @markle_metamorphosis_1992; @butler_growth_1996].  Markle et al. [-@markle_metamorphosis_1992] postulate that `r spp` larvae may extend settlement by delaying metamorphosis to avoid unfavorable oceanographic conditions.  

Based on research survey tows, Jacobson and Hunter [-@jacobson_bathymetric_1993] found that the catches of `r spp` in a given area and depth zone were not randomly distributed by sex, with males and females tending to occur in separate patches. Furthermore, `r spp` appear to undergo ontogenetic shifts in their distribution with fish gradually moving to deeper water as they grow [@jacobson_depth_2001].  Westrheim et al. [-@westrheim_stock_1992] summarized the results from multiple tagging studies between 1948 - 1979 indicated seasonal movements of `r spp` onto the continental shelf in the summer and off the shelf in the winter, but little evidence of north-south movement or appreciable mixing between Pacific Marine Fisheries Commission (PMFC) statistical areas. A few tagged fish moved long distances, however. For example, Westrheim and Morgan [-@westrheim_results_1963] reported that a fish caught and tagged in the Willapa Deep area off Washington was subsequently recaptured off Humboldt Bay, CA, 360 nautical miles south.  Barss et al. [-@barss_marine_1977] reported having records for 13 tagged fish that were recaptured after 10 or more years at liberty. The longest time a fish was at liberty was 22 years and was recaptured within 1 nautical mile of its original release location. Westrheim et al. [-@westrheim_stock_1992] noted the limited observed movement between PMFC areas (movement north and south) however, noted that a majority of the tagging work was done prior to the development of the deepwater trawl fishery for `r spp` (except PFMC area 1C).  Additionally, `r spp` larvae have an extensive pelagic period, greater than one year, which may allow larvae movement across the West Coast [@hagerman_biology_1952].

Ono et al. [-@ono_space-time_2016] examined movement patterns of `r spp` using \gls{s-wcgbt} data collected off the West Coast in early summer and early fall. They found that `r spp` displayed ontogentic movement, moving to shallower and deeper water during summer months. Additionally, `r spp` appeared to move from areas southwest areas of San Fransisco and northwest of Eureka to the northern or southern edges of the U.S. Coast in late summer, aggregating along the Washington coast and south of Point Conception [@ono_space-time_2016]. This movement pattern identified by Ono et al. [-@ono_space-time_2016] differs from the limited latitudal movement identified by early tagging studies of `r spp` [@westrheim_stock_1992].

Stock structure is not well understood and Westeheim et al. [-@westrheim_stock_1992] reports that conventional stock-recruitment assessments of `r spp` may be  unsuccessful due to non-intermingling adult stocks, but larvae probably intermingle during their long pelagic life.  Stepien [-@stepien_phylogeographical_1999] used sequences of mitochondrial DNA extracted from `r spp` sampled at six sites ranging from southern California to the Gulf of Alaska and found phylogeographical structure in west coast `r spp` with spatial clustering of genetically similar individuals. However, there were several unusual clusters of specimens having apparently similar genetic make-up although they were geographically separated (i.e., fish from Alaska with similar genetics as fish from San Diego).

Based on research survey tows, Jacobson and Hunter [-@jacobson_bathymetric_1993] found that the catches of `r spp` in a given area and depth zone were not randomly distributed by sex, with males and females tending to occur in separate patches. Furthermore, `r spp` appear to undergo ontogenetic shifts in their distribution with fish gradually moving to deeper water as they grow [@jacobson_depth_2001].  


## Ecosystem Considerations

Ecosytem factors have not been explicitly modeled in this assessment but there are several aspects of the California current ecosystem that may impact `r spp` population dynamics and warrant further research. Survival of `r spp` eggs and pelagic larvae that have a protracted pelagic phase are linked to water circulation patterns [@king_climate_2011]. The timing of settlement occurs typically between January and March and is correlated with Ekman transport, positive vertical velocity and relatively warm bottom temperatures [@toole_settlement_1997].  Markle et al. [-@markle_metamorphosis_1992] hypothesized that juvenile `r spp` move inshore to nursery habitat by making vertical ascents during the night off bottom until they encounter suitable habitat.  Tolimieri et al. [-@tolimieri_spatio-temporal_2020] identified multiple areas off the coast of southern California that had high densities of young `r spp`. This is consistent with the finding of Toole et al. [-@toole_seasonal_2011] that juvenile `r spp` 10 - 22 cm tended to move inshore during summer months. As `r spp` age they generally move offshore into deep waters. Changing water temperature due to climate change may alter the winter onshore Ekman transport which could have impacts on juvenile survival, result in distributional shifts of favorable spawning grounds, or nursery habitats of `r spp`.  


## Historical and Current Fishery Information

Trawl fishing with boats powered by sail began in California waters in 1876 and caught many flatfishes, including `r spp` [@hagerman_biology_1952].  Even though there are reports of `r spp` being sold in summer markets in San Francisco as early as 1878 (Lockington [-@lockington_report_1880] as referenced by Hagerman [-@hagerman_biology_1952]), it was not until the early part of the 20th century that landings of `r spp` were recorded.  In a 1936 biological report from the State of Washington Department of Fisheries `r spp` was described as "very slimy and is repulsive to handle" and "[i]t has no value as a commercial fish" [@smith_report_1936].  It was not long after 1936 that `r spp` were being landed in significant quantities up and down the U.S. west coast.  

While early `r spp` landings were first recorded in California, fisheries for `r spp` had developed in Oregon and Washington in the 1930's  (Table \ref{tab:allcatches} and Figure \ref{fig:catch}). Historically, the highest landings by state of `r spp` occurred in California. Starting around 1980 Oregon became the state with the highest landing of `r spp`. In California, in recent years the majority of removals of `r spp` have been landed in northern California ports (Eureka, Fort Bragg, and Crescent City). In Oregon the majority of recent landings occur at Astoria and Newport followed by Coos Bay and Brookings. In Washington that ports with the highest landings in recent years have been Bellingham and Westport.

`r spp` was considered a "repulsive" fish by some [@smith_report_1936] and was likely discarded as bycatch when pursuing other more desirable species such as petrale sole (_Eopseta jordani_) and English sole (_Parophrys vetulus_).  However, markets were eventually developed and landings began steadily increasing in the 1940's.  Landings remained relatively constant throughout the 1950s and 1960s before increasing rapidly into the early 1990s.  Subsequently, the landings declined (mostly in California) until 2007 when harvest guidelines increased the allowable catch based on the 2005 assessment results [@sampson_status_2005].  In 2015 the  Annual Catch Limit (ACL) of `r spp` increased from 25,000 to 50,000 mt for `r spp` with 95 percent of the ACL allocated to the trawl fishery. However, attainment of `r spp` has been low (less than 15 percent). The reasons for low attainment of `r spp` are complex. `r spp` co-occur with sablefish (_Anoplopoma fimbria_). Sablefish has been  a constraining species for `r spp` landings due to the lower ACLs of sablefish and allocation challenges among sablefish fishing sectors. Additionally, in recent years there has been an increased competition in the whitefish markets with other inexpensive fish options (e.g. tilapia and catfish) which may have displaced U.S. wild caught species such as `r spp` [@norma-lopez_is_2009].  

Groundfish trawl fisheries land the majority of `r spp` (greater than 99 percent total landings) while fixed gears, shrimp trawls, and recreational fisheries make up a very small amount of fishing mortality.  Shrimp trawls have been using excluders which have reduced bycatch of many species including `r spp`.  The trawl fisheries typically catch `r spp` while targeting the depwater complex consisting of `r spp`, sablefish, shortspine thornyhead (_Sebastolobus alascanus_), and longspine thornyhead (_Sebastolobus altivelis_, DTS deepwater complex) but also encounter `r spp` when targeting petrale sole or nearshore mix species. The fishery targets `r spp` across a range of depths (50 - 330 fathoms) depending upon the season (Scott Malvitch, personal communiction, ODFW).  

Historically, discarding of `r spp` occurred for a variety of reasons.  `r spp` was discarded due to trip limits, small size, or even being too large.  `r spp` of the largest size caught at deep depths  become "jellied" where the tissue becomes soft and has little marketability (Mike Okoniewski, personal communication). Since the introduction of individual fishery quotas (IFQ) in 2011, the discarding of all quota species, including `r spp`, has dramatically declined across the IFQ trawl fleet.  

## Summary of Management History and Performance

Management restrictions for `r spp` came largely into place in the early 1980's with the implementation of trip limits and quotas on DTS species, which mostly limited catches of `r spp` because of more restrictive trip limits on the higher priced sablefish and thornyheads. Trip limits specific for `r spp` were implement for portions of 1994, 1996, the start of 1997, and for years thereafter. The introduction of the IFQ fishery in 2011 created an allocation system of quota pounds to vessels participating in the catch share program for species in the groundfish Fishery Management Plan. Attainment of `r spp` in recent years has been low due to constraining ACLs and allocations for sablefish but also market competition with other whitefish products (i.e., tilapia).  Overall, `r spp` removals have well below the annual catch limits (ACLs) for `r spp` (Table \ref{tab:ofl}).


## Foreign Fisheries

`r spp` in Canadian waters are treated as two distinct stocks; a northern stock and a southern stock.  The fishery in the north began in the 1970's while the fishery off of the West Coast of Vancouver Island started in the late 1980's.  Area quotas were used to manage the two stocks until the introduction of individual based quotas in 1996.  A 1999 assessment reported that the stocks were being exploited at levels near the maximum sustainable yield [@department_of_fisheries_and_ocean_dover_1999].  The stock has not been assessed since, however, was slated for assessment in 2020. For the two areas combined (3C/D), the total allowable catch in recent years has been set at 1,375 mt [@department_of_fisheries_and_ocean_pacific_2019].

In the Gulf of Alaska the flatfish fishery has caught substantial quantities of `r spp`, with the peak of 9,740 mt in 1991 [@stockhausen_gulf_2006]. Gulf of Alaska catches or `r spp` have been well below the Total Allowable Catch (TAC) which was set at 9,501 in 2019 [@the_plan_team_for_the_groundfish_fisheries_of_the_gulf_of_alaska_stock_2019]. In 2020 the spawning biomass for `r spp` was estimated to be 27,935 mt, well above the biomass target for the Gulf of Alaska of 7,613 mt [@the_plan_team_for_the_groundfish_fisheries_of_the_gulf_of_alaska_stock_2019].  



