## Fishery-Dependent Data

### Recent Commercial Fishery Landings

The commercial removals were extracted from the Pacific Fisheries Information Network (PacFIN) database for 1981 - 2020 for California and Washington and 1987 - 2020 for Oregon on January 28, 2021. The majority of removals for `r spp` arise from trawl gear (i.e., greater than 99 percent). Commercial removals for all gear types were combined into two area-specific fleets: a California fleet and a combined Oregon/Washington fleet. This fleet structure was decided based on feedback received during the pre-assessment data webinar where combining Oregon and Washington was suggested due to similarities in fisheries and across state fishing and landing practices that make separating by state challenging.

#### Washington Prior to 1981

Historical commercial landings of non-shrimp trawl gear were reconstructed for `r spp` landed in Washington for use in the 2011 assessment by Greg Lippert (Washington Department Fish and Wildlife, WDFW).  Shrimp trawl, fixed gear, and recreational landings constitute a negligible amount of the total mortality for `r spp`.  Historical landings of `r spp` landed in the state of Washington were determined from various data sources using era-specific understanding of fishing behavior.  For details, please see Hicks and Wetzel [-@hicks_status_2011]. The historical landings for Washington were not revised for this assessment. 

#### Oregon Prior to 1986

Historical commercial fishery landings of `r spp` in Oregon for the years `r startyr` - 1986 were obtained from Alison Whitman (Oregon Department of Fish and Wildlife, ODFW). A description of the methods can be found in Karnowski et al. [-@karnowski_historical_2014]. The California catch reconstruction (discussed below, Ralston et al. [-@ralston_documentation_2010]) excluded fish that were caught in Oregon or Washington waters and landed at a California port. In contrast, Oregon's historical catch reconstruction was based on the port of landing. This disconnect between methods applied by California and Oregon was brought to light during the [2016 Catch Reconstruction workshop](https://www.pcouncil.org/documents/2017/03/i2_att1_catch_reconstruction_workshop_report_mar2017bb.pdf/).  Landings estimates between 1948 - 1968 for `r spp` that were identified to have occurred in Oregon or Washington waters and excluded from the California reconstruction were provided by John Field (Southwest Fishery Science Center, SWFSC, NOAA).  These landings of `r spp` were added to the Oregon/Washington fleet within the model. 


#### California Prior to 1981

Historical commercial fishery landings of `r spp` from 1948 - 1980 were obtained directly from E.J. Dick (SWFSC, NOAA) who retrieved the data from the California Cooperative Groundfish Survey data system (CALCOM). The method of reconstructing California historical landings are described by Ralston et al. [-@ralston_documentation_2010]. 

At present, no landing for `r spp` before 1948 are available in CALCOM.  For years prior to 1948, the landings from the 2005 assessment [@sampson_status_2005] were used (as was done in the 2011 assessment). The data from Sampson [-@sampson_status_2005] for the years of 1911 - 1947 include assumed discards of `r spp` from other fisheries operating at the time in California and represent total removals in comparison to the data from CALCOM account for only landed `r spp`. To account for this difference in the input catches for California a retention block was applied for 1911 - 1947 that assumed 100 percent retention (i.e., no additional discarding would be assumed since the removals during this period represent landings + discards). 

### Commercial Discards

Data on discards of `r spp` are available from a few different data sources.  Multiple historical discard studies were used in the model: estimates for the California trawl fishery discarding rate in 1992 (Humboldt State Study), Oregon at-sea discarding study between 1959 - 1961 [@hermann_results_1963], Pikitch discard study in Oregon and Washington between 1985 - 1987, 1974 discard rate analysis in Oregon (Methot et al. [-@methot_jr_assessment_1990] based on TenEyck and Demory [-@teneyck_utilization_1975]), and discard observations from the West Coast Groundfish Observer Program (WCGOP). 

Brodziak et al. [-@brodziak_assessment_1997] described a discard study during 1989 - 1996 by researchers from Humboldt State University. Across 28 observed trips in California waters a total of 21,950 pounds of `r spp` were discarded from a total catch of 172,737 pounds. The authors did not specify what portions of the discards were due to the small size of the fish versus due to trip limits. 

Hermann and Harry [-@hermann_results_1963] conducted a discard study in Oregon examining at-sea and landed length observation for multiple years between 1950 - 1961 (6 sampled years). The data consisted of length frequency measurements taken at-sea and comparable measurements taken at the docks, after sorting and discarding of small unmarketable fish. Retained and discarded fish were estimated by converting observations to pounds using average weights. Estimates of the total length distribution measured at-sea and landed fish were used in previous assessments of `r spp` [@sampson_status_2005; @hicks_status_2011]; however, these data were not available for evaluation in this assessment and were only included as 'ghost' observations (allows to see the implied data fits without being incorporated in the model likelihood estimation). Hermann and Harry [-@hermann_results_1963] report did include estimates of at-sea catches and landed `r spp` for each year. Discard rates for well sampled years, 1959 - 1961, were  retained for use in this assessment. The discarding rate per year ranged from 0.112 - 0.232.

Based on sampling at-sea during summer 1974 in Oregon waters, TenEyck and Demory [-@teneyck_utilization_1975] estimated age-specific retention rates and reported age-at-50-percent-retention of 7.4 years for male `r spp` and 6.9 years for females, equivalent to lengths at 50 percent retention of about 33 cm. Based on data from the 1974 study, Methot et al. [-@methot_jr_assessment_1990] reported that the fraction discarded on a weight basis was 0.167.

A trawl discard study conducted in 1985 - 1987, referred to as the Pikitch study, organized by Ellen Pikitch resulted in discard rates and length observations for various groundfish species including `r spp` [@pikitch_evaluation_1988]. The northern and southern boundaries of the study were $48^\circ 42^\prime$ N. latitude and $42^\circ 60^\prime$ N. latitude respectively, which is primarily within the Columbia INPFC area, falling within Oregon/Washington waters [@pikitch_evaluation_1988; @rogers_numerical_1992].  Participation in the study was voluntary and included vessels using bottom, midwater, and shrimp trawl gears.  Observers on commercial vessels collected the data, estimated the total weight of the catch by tow, and recorded the weight of species retained and discarded in the sample.  Results of the Pikitch discard study were processed and provided by John Wallace (personal communication, Northwest Fishery Science Center, NWFSC, NOAA) in the form of ratios of discard weight to retained weight of `r spp` and sex-specific length frequencies.   

The final data for discard rate and length observations is from the WCGOP.  This program is part of the NWFSC and has been recording discard observations starting in 2003. Since 2011, when the IFQ program was implemented, observer coverage rates increased to nearly 100 percent for all the limited entry trawl vessels in the program and discard rates declined compared to pre-2011 rates. Discard rates were obtained for both the IFQ catch-share (observed and electronic monitored vessels) and the non-catch share sector for `r spp`. A single discard rate was calculated by weighting discard rates based on the commercial landings by each sector.  Coefficient of variations were calculated for the non-catch shares sector and pre-catch share years by bootstrapping vessels within ports because the observer program randomly chooses vessels within ports to be observed. Post trawl rationalization, all catch-share vessels have 100 percent observer coverage and discarding is assumed to be known. 

The discard rates across all data sources for the California and the Oregon/Washington fleets are shown in Table \ref{tab:disc-rates} and Figures \ref{fig:ca-disc-ob} - \ref{fig:orwa-disc-len-ob-2}. The mean weights of discarded `r spp` from WCGCOP data are shown in Figures \ref{fig:ca-disc-wght-ob} and \ref{fig:orwa-disc-wght-ob}. The discard length observations from the Pikitch study (Oregon/Washington only) and WCGOP are shown in Figures \ref{fig:ca-disc-len-ob} and \ref{fig:orwa-disc-len-ob-2}. The observed lengths discarded and the overall discard rate by the California fleet in recent years appeared to have roughly two periods: 2011 - 2014 and 2015 - 2019. The discard rates from 2015 - 2019 were lower than the earlier IFQ years (Figure \ref{fig:ca-disc-ob}) with a higher proportion of smaller fish discarded (Figure \ref{fig:ca-disc-len-ob}, except 2017). The number of discard length observations in California in recent years (2015 - 2019, samples ranged from 82 - 733 per year) was lower than the earlier years (2011 - 2014, samples ranged from 618 - 1310 per year).  This may be due to both a decrease in discarding of `r spp` and increase in the number of vessels using electronic monitoring (EM) where EM vessels only carry observers 20 percent of the time. There was a similar decline in length discard samples from WCGOP for the 2015 - 2019 period for Washington/Oregon but not to the extent observed in California. However, the discard rates and length discarded in Oregon/Washington appeared relatively consistent across the IFQ period.    

The observed discard length observations by year and sex for `r spp` from the Pikitch study were limited. In order to reduce the noise in these data sex-specific observations were combined based on the assumption that discarding of small fish was not sex-specific (there was no indication of this in the data).    

### Commercial Fishery Length and Age Data

The PacFIN Biological Data System (BDS) contains data for `r spp` from ODFW (1987-present) and WDFW (1967- present), but only 1989 - present data from California Department of Fish and Game (CDFG). In contrast for California, the CALCOM database contains earlier length (1969 - 1988) and age samples (1981 - 1989) that are not currently available in PacFIN. Expanded length and age data from CALCOM for all years available were provided by E.J. Dick (personal communication, SWFSC, NOAA). Since there were early samples that were available in CALCOM and not PacFIN, the CALCOM expanded length and ages were used in this assessment. Early model sensitivities conducted reflected little difference in model estimates for `r spp`, a well sampled species with large landings, when the same years of data were used between PacFIN or CALCOM. 

Commercial length-frequency distributions based on the fishing year were developed for each state for years where observations were available. For each fleet, the raw observations (compiled from the PacFIN and CALCOM databases) were expanded to the sample level, to allow for any fish that were not measured, then to the trip level to account for the relative size of the landing from which the sample was obtained. The expanded length observations were then expanded by the landings in each state. Post-expanded length data were combined into a single fleet for Oregon/Washington. Age frequencies were computed in the same manner.

Length and age data collected from commercial landings for each state are summarized by the number of trips and fish sampled by year (Tables \ref{tab:com-len-samps} and \ref{tab:com-age-samps}). The lengths sampled by port for California are shown in Figure \ref{fig:ca-len-port} based on port information in PacFIN. While the model used length data from CALCOM due to the early years of data available, the years where CALCOM and PacFIN overlap the samples should be the same.  Length observations in California generally range between 30 - 50 cm with females consisting of a higher proportion of the larger sizes due to dimorphic growth (Figure \ref{fig:ca-len-data}). Observed average size had high large variance prior to 1988, due to lower input sample sizes, with the variance of observations in recent years being low (Figure \ref{fig:mean-ca-len-data}). The length composition data aggregated across years for the California fishery shows that a higher proportion of males are selected relative to females and the peak length of males selected is lower than the female peak size (Figure \ref{fig:agg-len-data}). 

The age samples by port in California are shown in Figure \ref{fig:ca-age-port} based on data in PacFIN. Due to limited ageing capacity no otoliths collected in California between 2010 - 2020 were read for this assessment. The majority of read ages for California were sampled from otoliths from fish landed at the Crescent City port, followed by samples from the Eureka and Fort Bragg ports. The mean age of sampled fish fluctuated between 11 and 17 years of age across years with available age data from California (Figures \ref{fig:ca-age-data} and \ref{fig:mean-ca-age-data}). The peak age observed in aged fish for males and females were around 10 years of age  (Figure \ref{fig:agg-age-data}). 

Length and age data collected from commercial landings for Oregon and Washington are summarized by the number of trips and fish sampled by year (Tables \ref{tab:com-len-samps} and \ref{tab:com-age-samps}). The length samples by port for Oregon and Washington are shown in Figure \ref{fig:or-len-port} and \ref{fig:wa-len-port}. The observed range of lengths by sex (and unsexed) combined between Oregon and Washington primarily range between 35 - 45 cm prior to 1985 then  slightly shift to a larger range of selected fish from 1985 - present (Figure \ref{fig:orwa-len-data}).  The mean lengths observed across available data years also show the increased variance in early year samples and the lower mean size observed, around 35 cm in recent years (Figure \ref{fig:mean-orwa-len-data}).  The length composition data aggregated across years for the Oregon/Washington fishery shows a higher proportion of males are selected relative to females, similar to that observed in California, but even more extreme with a sharp peak for males selected around 30 cm (Figure \ref{fig:agg-len-data}). For clarity, the aggregated length figure shows both female and unsexed lengths plotted in the top section of the fleet specific panel where the unsexed lengths are plotted behind the female lengths.  There  unsexed length compositions from Oregon/Washington were primarily from early data years. 

The otoliths read by port of collection for Oregon and Washington are shown in Figures \ref{fig:or-age-port} and \ref{fig:wa-age-port}. There are a reduced number of otoliths read from Oregon and Washington since the last assessment in 2011 due to limited ageing capacity (Table \ref{tab:com-age-samps}). The mean age of sampled fish across all years ranged between 11 and 14 years of age in Oregon and Washington (Figures \ref{fig:orwa-age-data} and \ref{fig:mean-orwa-age-data}). The peak age observed in aged fish for males and females was around 10 years of age similar to the California fleet observations (Figure \ref{fig:agg-age-data}).  

The input sample sizes for each fleet in the model were calculated via the Stewart method (Ian Stewart, personal communication):

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

To avoid double use of the length and age data from individual fish, the length and age data sources were each given 0.50 weight in the likelihood calculations when model fitting.  
