## Biological Data

### Natural Mortality

Natural mortality is a parameter that is often highly uncertain in fish stocks.  There are no current published estimates of natural mortality for `r spp`, aside from what has been used in previous assessments which were based upon maximum ages.  Assessments of `r spp` off the West Coast in 1997 and 2005 both fixed this parameter at 0.09 yr^-1^ for both males and females [@brodziak_assessment_1997; @sampson_status_2005]. The 2011 assessment estimated natural mortality at 0.117 yr^-1^ for females and 0.142 yr^-1^ for males [@hicks_status_2011]. 

The current method for developing a prior on natural mortality for West Coast groundfish stock assessments is based on Hamel [-@hamel_method_2015], a method for combining meta-analytic approaches relating the $M$ rate to other life-history parameters such as longevity, size, growth rate, and reproductive effort to provide a prior on $M$. This approach modifies work done by Then et al. [-@then_evaluating_2015] who estimated $M$ and related life history parameters across a large number of fish species from which to develop an $M$ estimator for fish species in general. They concluded by recommending $M$ estimates be based on maximum age alone, based on an updated Hoenig non-linear least squares estimator $M = 4.899A^{-0.916}_{\text{max}}$. Hamel [-@hamel_method_2015] re-evaluated the data used by Then et al. [-@then_evaluating_2015] by fitting the one-parameter $A_{\text{max}}$ model under a log-log transformation (such that the slope is forced to be -1 in the transformed space [@hamel_method_2015]), the point estimate and median of the prior for $M$ is:

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

\vspace{0.5cm}

where $A_{\text{max}}$ is the maximum age. The prior is defined as a lognormal distribution with mean $ln(5.4/A_{\text{max}})$ and standard error = 0.438.  The maximum age for `r spp` was selected based on available age data from all West Coast data sources (Figure \ref{fig:all-ages}). The oldest aged `r spp` was 69 years, captured by the commercial fishery in 1989, not accounting for potential ageing error. Examining all aged fish, a maximum age of 50 was selected. Across all data sources there were limited observation greater than 50 years of age (79 observations in total). In the fish that have been aged from the \gls{s-wcgbt} there have been 41 observations of fish greater than 50 years old (25 females and 16 males). There was little support for a sex-specific differences in maximum age. However, age data are subject to ageing error which could impact this estimate of longevity.  Using a maximum age of 50, the median of the prior was 0.108 yr^-1^ with a standard error of 0.438.
  

### Maturation and Fecundity

Estimates of maturity at length and age for `r spp` have been variable across historical studies. Hagerman [-@hagerman_biology_1952] reported that 50 percent of 35 cm female `r spp` were mature with 100 percent maturity-at-length of 45 cm. Yoklavich and Pikitch [-@yoklavich_reproductive_1989] reported a smaller size at 50 percent maturity. Hunter et al. [-@hunter_fecundity_1992] reported that different collection times and methods of analysis resulted in different estimates of maturity at length and suggest that differences reported between Hagerman [-@hagerman_biology_1952] and Yoklavich and Pikitch [-@yoklavich_reproductive_1989] may have been due to these differences rather than changes in maturity. Brodziak and Mikus [-@brodziak_variation_2000] found significant north-south differences in maturity curves derived for International North Pacific Fisheries Commission (INPFC) areas, with fish maturing at smaller sizes in the north. Their estimate of length at 50 percent maturity was less than 34.3 cm, as reported by Hagerman [-@hagerman_biology_1952].

The maturity-at-length assumed in this assessment was based on new `r spp` maturity reads conducted by Melissa Head (NWFSC, NOAA) examining a total of 428 from the \gls{s-wcgbt} (N = 309) and ODFW State sampling (N = 119). The coastwide 50 percent size-at-maturity was estimated at `r round(model$MGparmAdj[,"Mat50%_Fem_GP_1"][1], 1)` cm and a slope of `r round(model$MGparmAdj$Mat_slope_Fem_GP_1[1], 2)` with maturity asymptoting to 1.0 for larger fish. The shape of the new maturity-at-length curve and a comparison to the maturity curve used in the 2011 assessment is shown in Figure \ref{fig:compare-mat-at-len}. The new maturity-at-length curve was based on the estimate of functional maturity, an approach that classifies maturity with developing oocytes as mature or immature based on the proportion of vitellogenin in the cytoplasm and the measured frequency of atretic cells (Melissa Head, personal communication, NWFSC, NOAA). 

Spatial difference in life history traits is commonly observed in groundfish species off the West Coast. Maturity-at-length was examined spatially splitting `r spp` samples into north and south of Point Reyes off the California coast (approximately $38^\circ 0^\prime$ N. lat.). The latitudinal split was selected prior to examining the data and in a somewhat arbitrary fashion, with the decision driven by the number of samples available by area and based on work by Tolimieri et al. [-@tolimieri_spatio-temporal_2020] which identified areas of high age-1 `r spp` density. The northern group had 334 maturity samples and the southern group had 94 maturity samples. The estimated length at 50 percent maturity was significantly different for fish in the north and south, with fish in the south maturing at larger sizes (39.84 cm) relative to fish in the north (31.23 cm, Figure \ref{fig:spat-mat-at-len}). These results are consistent in trend with those from Brodziak and Mikus [-@brodziak_variation_2000] who also determined that fish in the north appear to mature at smaller sizes relative to fish in the south. However, the measured variation in maturity-at-length by area in Brodziak and Mikus [-@brodziak_variation_2000] was less extreme (Coastwide: 33.4 cm, Vancouver: 28.2 cm, Columbia: 32.0 cm, Eureka: 34.6 cm, Monterrey: 35.3 cm) compared to the current estimates north and south of Point Reyes. Spatial estimates of biomass north and south of Point Reyes, using \gls{s-wcgbt} data averaged across the most recent five years, indicated that approximately 67 percent of the West Coast `r spp` biomass is estimated to be north of Point Reyes.

The size and age of fish observed in shallower depths (less than 400 m) varies between the north and south (Figure \ref{fig:samples-north-south}). In the north a wide range of sizes and ages are observed at shallower depths, while only younger and smaller fish are observed at shallower depths in the south. This pattern in sizes and age are also apparent when looking at all observations of `r spp` by the \gls{s-wcgbt} (Figure \ref{fig:fish-by-lat}) with a distinct break in observations around San Francisco, just south of Point Reyes. The mechanisms leading to these differences across the coast are unclear. Future work should be done to determine if maturity-at-length or -age slowly change across latitudes or if there are distinct changes by area.    

This assessment did not account for these spatial differences in maturity and assumed a homogeneous population structure for `r spp` off the West Coast due to challenges in the ability to split data by area combined with the uncertain spatial migration patterns of `r spp` off the West Coast. The new maturity-at-length estimates were concluded approximately two months prior to the assessment deadline which provided time to incorporate the new estimates in the base model. However, the time was not sufficient to adequately evaluate the viability of creating a spatial model for `r spp`. Future analysis should be conducted to further understand potential patterns in life history traits across the coast combined with tagging studies which could provide insight in movement.    

Fecundity is related to body size of `r spp`. Yoklavich and Pikitch [-@yoklavich_reproductive_1989] estimated fecundity of `r spp` off the Oregon coast reporting that a 40 cm female produces about 40,000 oocytes and a 55 cm female produces about 160,000 oocytes.  Hunter et al. [-@hunter_fecundity_1992] estimated the fecundity of `r spp` samples off the coasts of Oregon and California and found no statistical difference in the fecundity by area and estimated no statistical difference in Oregon between their results and those from Yoklavich and Pikitch [-@yoklavich_reproductive_1989].

The relationship of fecundity to weight concluded by Yoklavich and Pikitch [-@yoklavich_reproductive_1989] was nearly linear when translated from length to weight. Based on the work of Yoklavich and Pikitch [-@yoklavich_reproductive_1989] fecundity was assumed to be equal to body weight in this assessment (e.g., spawning output equal to spawning biomass).  


### Length-Weight Relationship

Weight-at-length data collected by the \gls{s-wcgbt} were used to externally estimate a weight-length relationship for both sexes of `r spp`. Weight-at-length was generally similar between females and males (Figure \ref{fig:est-len-wght}). Males were estimated to marginally weigh more at the larger lengths (> 50 cm) compared to females.  However, the majority of observations of fish greater than 50 cm are predominated by female fish because males generally do not tend to grow as large in comparison. The following estimate of the weight-at-length relationship was used by sex in this assessment:

\begin{centering}

Females: $\alpha$ = `r format(model$MGparmAdj$Wtlen_1_Fem[1], scientific = TRUE, digits = 3)`; $\beta$ = `r round(model$MGparmAdj$Wtlen_2_Fem[1], 2)`

Males: $\alpha$ = `r format(model$MGparmAdj$Wtlen_1_Mal[1], scientific = TRUE, digits = 3)`; $\beta$ = `r round(model$MGparmAdj$Wtlen_2_Mal[1], 2)`

\end{centering}

\vspace{0.50cm}

where weight is measured in grams and length in cm.

### Growth (Length-at-Age)

The length-at-age was estimated for male and female `r spp` using data collected from the \gls{s-wcgbt} survey. Figure \ref{fig:est-len-at-age} shows the lengths and ages for all years and all data as well as predicted von Bertalanffy fits to the data. Females grow larger reaching a maximum around 48 cm, while males reach maximum size around 43 cm. However, there is considerable variation in length-at-age for both sexes. 

Brodziak and Mikus [-@brodziak_variation_2000] reported differences in growth curves between some INPFC areas using data collected on the continental slope (183 - 1,280 m).  Using data collected during the \gls{s-wcgbt} (55 - 1,280 m) variation in length-at-age was investigated for four different regions along the coast: south of Point Conception, north of Point Conception to the California/Oregon border, Oregon, and Washington.  Figure \ref{fig:est-len-at-age-region} shows the differences between female and male growth curves in each of these areas. The $L_{\infty}$ for males south of Point Conception was the largest of the areas, although the differences in maximum size were relatively small. The difference in sizes for females was also minimal, with females generally reaching larger sizes in the northern areas. 

Coastwide sex-specific growth parameters were initially estimated external to the model at the following values:

\begin{centering}

Females $L_{\infty}$ = 48.5; $L1$ = 11.1 cm; $k$ = 0.117 per year

Males $L_{\infty}$ = 43.1 cm; $L1$ = 15.5 cm; $k$ = 0.106 per year

\end{centering}

\vspace{0.50cm}

These values were used as starting parameter values within the base model prior to estimating each parameter for male and female `r spp`.

The \gls{s-wcgbt} was used to examine the variation in length-at-age by year. The base model assumes that length-at-age and weight-at-age were static across the modeled years.  However, if there are significant variations in growth by year that are not accounted for in the model, this could result in bias parameter and model estimates due to the model attributing patterns in the data to other sources (e.g., recruitment, growth parameters). Variations in growth by year could result from annual recruitment strength or positive and negative oceanographic conditions. The \gls{s-wcgbt} data did not indicate large meaningful variations in observed length-at-age or weight-at-age across the survey years (Figures \ref{fig:tv-len-at-age} and \ref{fig:tv-wght-at-age}). 


### Sex Ratio

The sex ratio observed by depth showed interesting patterns. First, because males grow to a smaller size, the proportion of females at intermediate lengths is less than 50 percent, and is 100 percent at larger lengths (Figure \ref{fig:sex-by-len}). This inter-plays with the pattern of larger fish in deeper water and results in fewer females at intermediate depths (250-750 m) and nearly all females in the deepest depths (Figure \ref{fig:fem-by-lat-depth}).  Sex ratio was slightly variable over latitude but showed no specific pattern (Figure \ref{fig:fem-by-lat-depth}). The assessment assumed a sex ratio of 50:50 at the time of settlement. 

### Ageing Precision and Bias

Uncertainty surrounding the age-reading error process for `r spp` was incorporated by estimating ageing error by age. Age composition data used in the model were from break-and-burn otolith reads. In the early years of data, ages were based on scale reads. However, after examining the distribution of ages by length, there were concerns about the potential bias in these data (Figure \ref{fig:scale-age}). These age reads were not used in the base model and were not used in the 2005 or 2011 assessments of `r spp`.  

Aged `r spp` used in the assessment were aged by either the Cooperative Ageing Project (CAP) in Newport, Oregon or the California Department of Fish and Wildlife (CDFW). Otoliths collected by each survey, Oregon fishery, and Washington fishery data were read by the CAP ageing lab. Otoliths collected from the California fishery were aged by CDFW.  Within-lab ageing error was estimated for both CAP and CDFW. Break-and-burn double reads of more than 8,000 otoliths were provided by the CAP lab (unpublished data) and 160 double reads from CDFW (unpublished data).  An ageing error estimate was made based on these double reads using a computational tool specifically developed for estimating ageing error [@punt_quantifying_2008] and using release 1.1.0 of the R package \href{https://github.com/nwfsc-assess/nwfscAgeingError}{nwfscAgeingError} [@thorson_nwfscageingerror:_2012] for input and output diagnostics. A linear standard error was estimated by age where there is more variability in the age of older fish (Figure \ref{fig:age-error}). Sensitivities to alternative ageing error estimates (curvilinear relationship with age) were conducted during model development and the model was relatively insensitive to alternative ageing error assumptions. 


## Environmental and Ecosystem Data

This assessment did not explicitly incorporate environmental data. 