# Assessment Model

## Summary of Previous Assessments and Reviews


### History of Modeling Approaches 

The previous assessment of `r spp` was conducted in 2011 [@hicks_status_2011] estimated the fractio unfished of `r spp` off the U.S. west coast at 84 percent, well above the target biomass (25 percent of unfished).  The 2011 assessment modeled the `r spp` using three state-specific fishing fleets with four fishery-independent surveys. The model estimated sex-specific natural mortality, growth, and selectivity. The 2011 assessment of `r spp` included some new concepts, mainly new features of Stock Synthesis at the time. Selectivity curves for both slope surveys were modeled using cubic splines which allows for greater flexibility in the shape of selectivity. The sex-specific selectivities were estimated where female selectivity was not forced to asymptote at 1.0, allowing for the possibility of differential maximum selection by sex. The estimate of spawning biomass of 393,507 mt in 2011 was highly uncertain the 95 percent confidence interval ranging between with the 81,000 - 705,000.  This estimated stock size was considerably higher than the final year spawning biomass in from the 2005 assessment of 188,987 mt.

The 2005 assessment of `r spp` also concluded that the biomass of `r spp` off of the U.S. west coast was well above the target biomass (40 percent management target at that time), at 63 percent of unfished biomass [@sampson_status_2005].  The 2005 assessment assumed a different fishery fleet structure from that used in 2011. Two fisheries fleets, a southern fleet from Eureka to Conception and a northern fleet from U.S. Vancouver to Columbia based on International North Pacific Fisheries Commission was assumed, with sex-specific, domed selection curves based on length for each fleet. This assessment used three survey time-series with dome-shaped sex-specific selectivity with female `r spp` never being fully selected (maximum selectivity less than 1.0).


### Response to the 2011 STAR Panel Recommendations and SSC 

*General Research Recommendations*

**Recommendation**: Complete and review the Washington catch reconstruction and review the California and Oregon catch reconstructions. The accuracy and wide availability of consistent basic information is essential to the development of Pacific coast assessments. In addition to the raw data, the reliability and availability of more spatially dis-aggregated forms of the data should be investigated to determine if they could be used to develop more spatially explicit models without causing sacrifices in accuracy.

**Response**: In 2016 a [groundfish historical catch reconstruction workshop](https://www.pcouncil.org/documents/2017/03/i2_att1_catch_reconstruction_workshop_report_mar2017bb.pdf/) was held to review catch reconstructions (landings prior to 1981) for California, Oregon, and Washington. During this workshop a divergence in approaches between California and Oregon catch reconstructions was identified. The California catch reconstruction did not include fish caught north of the California/Oregon border by trawlers that landed at ports in California between 1948 - 1968 and these fish were not accounted in the Oregon catch reconstruction. Flatfish (petrale sole and `r spp`) were approximately 75 percent of these landings. Estimates of these landings attributed to `r spp` were provided by Dr. John Field and were added to historical catches for the Oregon/Washington fleet in this assessment. Additionally, while California has created catch reconstruction for many species going back to the early 1900s, `r spp` historical catches are not available prior to 1948.  Future assessments of `r spp` would benefit from extending the catch reconstruction to earlier years, especially for species that have experienced long time series of exploitation. WDFW is still undertaking efforts to develop historical catch reconstructions for groundfish species landed in Washington's waters and significant progress has been made. After discussions with WDFW it was determined that the historical catches used in the 2011 assessment still represented the best estimates of `r spp` removals. 


**Recommendation**: The difficulties encountered in the `r spp` assessment and some other flatfish assessments with respect to the linkage between selectivities require addressing. Although in many instances sized based selectivity may be appropriate, when sexes separate spatially there is a requirement for models to at least be able to investigate complete independence between genders. It is important that this be implemented in an updated version of Stock Synthesis.

**Response**: Stock Synthesis now provides additional flexibility in the parameterization of sex-specific selectivity curves for both the double normal and logistic selectivity functions. To take advantage of this new flexibility fleets in this assessment assumed double normal selectivity parameterization.  The new approach in Stock Synthesis allows the user to specify a sex (male or female) to apply the main parameter lines with the other sex being estimated as offsets from the main selectivity curve.  The offset selectivity estimates sex-specific parameters for the peak, ascending width, descending with, final selectivity, and a scale parameter.   


**Recommendation**: The panel investigated the use of age-specific natural mortality in both assessments presented during the STAR panel. In each case, one of the reasons for exploring different mortality schedules was the difficulty in fitting the imbalanced abundance at age information (as seen through residuals to fits), either in the sex ratio at older ages (`r spp`) or the ratio of young to old fish (sablefish). The use of Lorenzen M based on a decline in natural mortality by the inverse of the growth rate implies a link with predation; however, wider use and development of some guidance on the appropriateness of the implementation in other stock assessments should be investigated.

**Response**: Alternative parameterization of natural mortality by age and sex were explored during model development. Assuming either Lorenzen natural mortality or linear changes in natural mortality at age had limited impact in model estimates and generally did not result in large improvements in the fits to data. Estimating natural mortality for `r spp` was challenging in general due to variable observations by sex, size, and age resulting from complex ontogenetic movement patterns.


**Recommendation**: Currently the only available error distribution for age information is the multinomial probability function. It appears that this may have some impact with respect to underestimating strong year classes and it would be desirable to explore the use of alternative error assumptions in order to analyze survey information, in particular where variance estimates in catches-at-age may be less than independent on abundance.

**Response**: The current verion of Stock Synthesis now allow for either multinomial or a Dirichlet Multinomial error distribution (linear or saturation). Both of the Dirichlet Multinomial parameterizations were explored during model development. The Dirichlet Multinomial approach in Stock Synthesis incorporates data weighting via an estimated parameter into the error distribution. The estimated parameter for data weight for each data source and type had issues of hitting the upper data weight bound (1.0). This method does not appear to work as intended for `r spp`.       


**Recommendation**: There should be new studies of maturity by length and age based on more comprehensive coastwide and depth-based sampling and using histological techniques for determining maturity stage. Given that there is uncertainty regarding the temporal stability of maturity schedules, there should be periodic monitoring to explore for changes in maturity.

**Response**: A new coastwide estimate of functional maturity was developed for use in this assessment.  The new functional maturity estimate of length at 50 percent maturity was similar to the assumed maturity in the 2011 assessment, however, the new slope reflected a more gradual increase in maturity-at-length. This new analysis also identified large spatial differences in maturity-at-length and -age spatially north and south of Point Reyes in California. This assessment did not explicitly account for this potential difference in maturity-at-length due to limited information on `r spp` movement patterns (latitudal or/and water depth).  Additionally, the fine scale information of historical data (catches, lengths, and age) creates challenges from splitting data by area.  Additional, research should be conducted to evaluate movement and the variation in life history traits in `r spp` off the West Coast to improve future assessments. 


**Recommendation**: Update the STAR Terms of Reference (TOR) to ensure that assessment documents include standard plots (or tables) of likelihood profiles that include likelihood components by data source and fleet. Such plots are an important diagnostic tool for displaying tensions among data sources profiles. 

**Response**: The groundfish assessment TOR now requires standardized tables and figures and are provided in this assessment. Likelihood tables with the contribution by data type for the base model and each sensitivity are provided.

*Recommendations Specific to `r spp`*

**Recommendation**: Researching ageing error, particularly aging bias, is important for `r spp` given the current base models difficulty with reconciling some tensions between different data sources regarding the sex ratio at the oldest ages. In addition, the ability of the model to track cohorts accurately would be significantly disrupted if there were severe size-based bimodality in cohorts caused by vastly different times of settlement (`r spp` are thought to have a larval period of 6 - 18 months). Consequently, larval period should also be examined.

**Response**: A new ageing analysis was conducted for otoliths read by the CAP lab and CDFW. The ageing error analysis for otoliths read by the CAP lab consisted of over 8,000 double reads of `r spp` otoliths. The ageing error analysis for otoliths read by CDFW used the same data that were available in 2011. In regards to age at settlement, Stock Synthesis now provides the ability to account for this explicitly.  A range of alternative age at settlement and timing were explored during model development. Model fits to data did not appreciably improve across these sensitivities.  Additionally, estimates across models were similar with the base model where the main difference appeared to be the years associated with particular recruitment deviation.    


**Recommendation**: For the \gls{s-wcgbt}, raw age and length information appeared to imply persistently different sex ratios when viewed in isolation. The concern is that there is some unrepresentative sampling occurring in the age distribution as ages are sub-sampled from length. The sampling procedure should be investigated more closely and potentially improved.

**Response**: Examinations of the \gls{s-wcgbt} data were conducted examining the observations by sex across depths and examining potential non-representative sampling by sex, length, and age.  The sex ratio across depths for `r spp` are approximately 50:50 at shallower depth sampled by the survey, shifting to a higher proportion of males observed in mid-depths (300 - 800 m), and then shifting to a higher proportion of females at the deepest depths. This sex ratio pattern was observed across all of the four surveys used in this assessment implying a biological mechanism rather than non-representative sampling. 

**Recommendation**: The conclusions of the NMFS workshop on developing priors on catchability were not available to the Panel. These should be made available and the information reconsidered specifically with respect to `r spp`, in an attempt to reconcile the relatively low catchability estimates for the surveys, particularly the NWFSC WCGBT survey which is thought to cover the majority of the stock distribution.

**Response**: Unfortunately, there is still limited guidance regarding what catchability values by survey and species would be considered reasonable or expected. The derived catchability in this base model for the \gls{s-wcgbt} was greater than the 2011 value (0.69). The catchability for the \gls{s-wcgbt} fluctuated above and below 1.0 within models explored during development of the base model. This change in the catchability was not driven by a single change in the model structure but due to an aggregate of minor changes (i.e., combine Oregon and Washington into a single fleet, update and reprocess data based on current methodologies, if natural mortality was estimated). 


**Recommendation**: Having simplified the model compared to previous assessments, especially with respect to uniform growth, it is important to continue investigating if this is likely to introduce undesirable levels of bias into the assessment process as more information becomes available. Spatial information on the distribution by age/size of females, particularly in the southern part of the range, particularly across the stratification boundaries of the survey as well as between stocks, should be the primary focus of this work. 

**Response**: This is an area of needed ongoing research. 


### Response to 2021 Groundfish Subcommittee Requests 

To be completed after the STAR panel.

