## Model Structure and Assumptions

### Modeling Platform and Structure

The assessment was conducted used Stock Synthesis version 3.30.16 developed by Dr. Richard Methot at the NOAA, NWFSC [@methot_stock_2013]. This most recent version was used because it included improvements and corrections to older model versions.  The previous assessment of `r spp` also used Stock Synthesis but an earlier version, 3.21f; model bridging was performed between both versions of Stock Synthesis and discussed below.  The R package [r4ss](https://github.com/r4ss/r4ss), version 1.38.0, along with R version 4.0.1 were used to investigate and plot model fits. 

### Model Selection and Evaluation

The base assessment model for `r spp` was developed to balance parsimony and realism, and the goal was to estimate a spawning output trajectory for the population of `r spp` off the west coast of the U.S. The model contains many assumptions to achieve parsimony and uses many different sources of data to estimate reality. A series of investigative model runs were done to achieve the final base model.

### Model Changes from the Last Assessment 

The assessment model structure was similar to that used in 2011, but there were a few meaningful changes to the model structure.  

First, in 2011 the options for estimating sex-specific selectivity were more restrictive than those available for use in this assessment. This assessment used the double normal selectivity parameterization for both fishery, \gls{s-tri}, and \gls{s-wcgbt} fleets in the model where the female sex-specific selectivity parameters were estimated as full offsets with a scale parameter relative to the male selectivity (offset parameters for the peak, ascending width, descending width, final selectivity, and a scale parameter).  In contrast, the option used in the 2011 assessment (the only available option in Stock Synthesis at the time) allowed for offset sex-selectivity estimation; however, the scaling of selectivitities by sex were linked based on user inputs (i.e., referred to as "dogleg" parameterization where two parameters estimate the relative difference in log-space for male selectivity). Male `r spp` were generally determined to have a higher selectivity likely due their shallower depth distribution compared to females.  After model exploration, selectivity of both slope surveys, \gls{s-nwslope} and \gls{s-aslope}, were modeled using a cubic spline selectivity form, same as was done in the 2011 assessment. The use of the cubic spline selectivity allowed better fits to the length composition data which appeared to have bimodality across female `r spp` sampled. Both of these surveys observed a higher frequency of females compared to the other data sources, likely related to the deep water sampling design of these surveys, and male selectivity was estimated relative to female selectivity (i.e., estimated via dogleg parameterization).   

This assessment simplified the fleet structure by collapsing data and catches from Oregon and Washington into a single fleet. Vessels fishing out of Oregon and Washington often fish across state lines where the landed state port may not accurately reflect the area of removals. During the pre-assessment data webinar state representatives from WDFW and ODFW supported the aggregation of data from these states into a single fishing fleet within the model.  

A minor change in parameterization from the 2011 assessment was the change in estimating male biological parameters (natural mortality, growth) as offsets from the female parameters. The 2011 assessment STAR panel expressed concerns regarding potential confounding between the estimation of sex-specific selectivity and natural mortality. Switching to a biological offset parameterization creates a linkage between parameters by sex. The 2011 assessment determined that the estimates of natural mortality by sex were highly uncertain; however, joint likelihood profiles showed that the difference in natural mortality by sex was well defined.  An offset parameterization provides the flexibility to estimate all sex-specific natural mortality and growth parameters or to fix a parameter by sex (typically females) and only estimate the relative difference to the fixed parameter for the other sex. 

Data weighting approaches and application have evolved considerably since 2011 when the last assessment of `r spp` was conducted. Currently, there are three alternative approaches for data weighting that have been approved for West Coast groundfish stock assessments: 1) Francis method, 2) McAllister Ianelli Harmonic Mean method, or 3) Dirichlet-Multinomial method. The base  model was weighted using the "Francis method", which was based on equation TA1.8 in Francis [-@francis_data_2011]. This formulation looks at the mean length or age and the variance of the mean to determine if across years, the variability is explained by the model. If the variability around the mean does not encompass the model predictions, then that data source should be down-weighted. This method accounts for correlation in the data (i.e., the multinomial distribution). Sensitivities were performed examining the difference in weighting using McAllister Ianelli Harmonic Mean Weighting [-@mcallister_bayesian_1997] and the Dirichlet Multinomial Weighting [-@thorson_model-based_2017].

The final major changes relative to the 2011 assessment was the treatment of select biological parameters: natural mortality and the maturity-at-length.  The maturity-at-length was updated based on new research conducted by Melissa Head (NOAA, NWFSC). The new estimate was based on a relatively new concept of functional maturity, an approach that classifies maturity with developing oocytes as mature or immature based on the proportion of vitellogenin in the cytoplasm and the measured frequency of atretic cells. 

The method of developing a natural mortality prior has changed since the last assessment conducted in 2011.  The current approach used for stock assessments of West Coast groundfish is based on Hamel [-@hamel_method_2015]. Additionally, this assessment did not estimate female natural mortality and fixed the parameter at the median of the prior, 0.108 yr^-1^. During model development the estimate of female natural mortality was deemed to be unrealistic due to low parameter estimates (around 0.08 yr^-1^) which did not appear to be supported by the data. However, the relative difference in the natural mortality between male and female `r spp` appeared to be well defined.  Using the offset parameterization allowed for the estimation of male natural mortality only in the base model.  The 2011 assessment freely estimated (no offsets) sex specific natural mortality values (female = 0.116 yr^-1^ and male = 0.143 yr^-1^).    


### Bridging Analysis

The exploration of models began by bridging from the 2011 assessment to Stock Synthesis version 3.30.16, which produced minor differences in scale but a similar status (Figures \ref{fig:bridge-ssb} and \ref{fig:bridge-depl}). The data bridging process, where data were updated through 2010, were updated in a step-wise additive fashion where the fleet structure was first modified (e.g., change to two fleets compared to three state-specific fleets used in 2011), then catches, indices, discard rates and mean weights, lengths, and ages were updated in that order. The model that included all updated data, labeled "Age" in Figure \ref{fig:bridge-ssb}, also included data weighting according to the McAllister Ianelli method. The estimated stock scale dropped relative to the 2011 bridge model when the fleet structure was revised, declined further when discard rates were updated, but increased when lengths and ages were updated with the final scale and status similar to the 2011 model (Figures \ref{fig:data-bridge-ssb} and \ref{fig:data-bridge-depl}). 

The next step in the model bridging analysis was to update all data sources through 2020 and apply a current data weighting method. The catches, indices, lengths, ages, and discard data (rates, mean weights, and discarded length observations) through 2020 were all added to the model in an additive step-wise fashion. The length and age data for the California fleet reflect the data available in PacFIN because CALCOM data used in the final model were not available at the time. The estimated spawning output had large fluctuations, below and above, the 2011 estimated time series, based on each updated data set (Figure \ref{fig:all-data-bridge-ssb}). The model with all data extended through 2020 and data weighted estimated a slightly higher scale but was relatively similar with the 2011 assessment estimate. The estimated relative stock status across models ended up with similar final estimates in 2011 (Figure \ref{fig:all-data-bridge-depl}), although showed alternative trajectory patterns during the interim years.

The final step in the model bridging evaluated the impact of updated biological parameter starting values, updated prior value for natural mortality, switching to estimating female biological parameters as offsets from males, and updating all fishery and survey selectivity parameterization using the double-normal selectivity pattern with females estimated as offsets from males (this included both slope surveys which assumed a cubic spline selectivity in the base model).  All changes were done in an additive fashion.  Updating the starting biological parameters and prior for natural mortality resulted in limited changes in the model relative to the "Update - 2020 All Data" model (Figures \ref{fig:structure-bridge-ssb} and \ref{fig:structure-bridge-depl}). Switching to estimate male biological parameters as offset from the female parameters resulted in a down-ward shift in the estimated scale of the stock. The final model bridging comparison updated the parameterization of sex-specific selectivity resulted in a significant decrease in the uncertainty of the estimated stock scale, and with the relative stock status more depleted compared to previous model updates (Figure \ref{fig:structure-bridge-ssb} and \ref{fig:structure-bridge-depl}). The selectivity form used in this model bridging reflects the initial parameterization with females estimated as offsets for all fleets and maximum female selectivity being less the 1.0. The final model was updated from this initial parameter structure based on numerous model explorations but this comparisons shows the general impact of the initial switch to the new selectivity assumptions.


### Key Assumptions and Structural Choices

The specifications of the assessment are listed in Table \ref{tab:model-structure}. The model is a two-sex, age-structured model starting in `r startyr	` with an accumulated age group at 60 years. Growth and natural mortality were assumed time invariant with constant growth estimated and female natural mortality fixed at the median of the prior and the relative offset of male natural mortality was estimated. The lengths in the population were tracked by 1 cm intervals and the length data were binned into 2 cm intervals. Stock Synthesis estimates growth in the age and size plus group. To avoid issues with additional estimated growth in the plus groups, the selection of the maximum age and length bins were selected to ensure that the numbers of fish in the plus group would be low. 

Time blocks on selectivity and retention parameters were used to allow for shifts in selectivity and retention curves. Time blocks for the peak of the selectivity parameter for the California and Oregon/Washington fleet were `r startyr` - 1984, 1985 - 1995, and 1996 - `r endyr + 1`. These blocks were based on what seemed to be large scale management changes to the DTS fishery but were also influenced by choices in previous `r spp` assessments [@sampson_status_2005; @hicks_status_2011]. Time blocks for the fishery retention in Oregon/Washington were `r startyr` - 1988, 1989 - 2003, 2004 - 2010, and 2011 - `r endyr + 1`. California did not have as much historical discard data, thus the time blocks on retention for this fleet were defined as `r startyr` - 2003, 2004 - 2010, 2011 - 2014, and 2015 - `r endyr+1`. The 2011 - 2014 and 2015 - `r endyr+1` retention blocks for the California fleet were based on observed changes in the discard rates and lengths from WCGOP between the early IFQ and recent IFQ years.

The specification of when to estimate recruitment deviations is an assumption that affects the estimate of early model uncertainty around stock scale and status. Recruitment deviations were estimated from 1880 - 2018 to appropriately quantify uncertainty in the early model years. The earliest length-composition data occur in 1967 and the earliest age data were in 1981. The most informed years for estimating recruitment deviations were from about the mid-1990s to 2014. The period from 1880 - 1974 was fit using an early series with little or no bias adjustment, the main period of recruitment deviates occurred from 1975 - 2018 with an upward and downward ramping of bias adjustment, and 2019 onward were fit using forecast recruitment deviates with no bias adjustment. Methot and Taylor [-@methot_adjusting_2011] summarize the reasoning behind varying levels of bias adjustment based on the information available to estimate the deviates. The standard deviation of recruitment variability was assumed to be `r model$parameters[model$parameters$Label == "SR_sigmaR", "Value"]` based on the estimated variation in recruitment from the base model.

The following distributions were assumed for data fitting: survey indices were lognormal, total discards applied a t-distribution with 30 degrees of freedom, and the compositional data had a multinomial error structure.


### Priors

Priors were applied only to parameters for steepness ($h$) and natural mortality ($M$). The steepness prior is based on the Myers [-@myers_maximum_1999] meta-analysis of flatfish steepness and the natural mortality prior is based on a meta-analysis completed by Hamel [-@hamel_method_2015]. The prior for steepness assumed a beta distribution with a mean equal to 0.80 and a standard deviation of 0.09 (Figure \ref{fig:h-prior}). 

The prior distribution for natural mortality was based on the Hamel [-@hamel_method_2015] meta-analytic approach with  an assumed maximum age of 50 years for both males and females. The prior assumed a log normal distribution for natural mortality with a median of 0.108 yr^-1^ and a standard error of 0.438 (Figure \ref{fig:m-prior}). 


### Data Weighting

Length data from the four surveys, conditional age-at-length compositions from the \gls{s-wcgbt} and \gls{s-nwslope}, and length and marginal age compositions from the fishery fleets were fit and appropriately weighted within the model. Length and marginal age data started with a sample size determined from the equation listed in Section \ref{commercial-fishery-length-and-age-data} for both fishing fleets in the model. Input sample sizes for survey length data were calculated according to the method described in Section \ref{nwfsc-wcgbt}.  It was assumed for age-at-length data that each age was a random sample within the length bin and the model started with a sample size equal to the number of fish in that length bin.

Extra variability parameters were estimated and added to the input variance for the indices of abundance for three surveys in the model; 1) \gls{s-tri} both early and late, 2) \gls{s-nwslope}, and 3) \gls{s-aslope}. Estimating additional variance for the \gls{s-wcgbt} was explored and determined to not be required. WCGOP discard rate data during the pre-IFQ period (prior to 2011) were bootstrapped to provide uncertainty of the total discard rate estimates. The IFQ fishery starting in 2011 has 100 percent observer coverage and a low default uncertainty of 0.05 was assumed for discard rates from 2011 - `r endyr+1`.

The base assessment model was weighted using the Francis method, which was based on equation TA1.8 in Francis [@francis_data_2011]. Sensitivities were performed examining the difference between the McAllister Ianelli [@mcallister_bayesian_1997] method (Harmonic Mean weighting) and the Dirichlet Multinomial Weighting [-@thorson_model-based_2017]  approaches. The weights applied to each length and age data set for the base model are shown in Table \ref{tab:dw} under the Francis method column.


### Estimated and Fixed Parameters

There were 229 estimated parameters in the base model. These included one parameter for $R_0$, 10 parameters for growth, 1 parameter for male natural mortality, 3 parameters for extra variability for the survey indices, 61 parameters for length-based selectivity, retention, and time blocking of the fleets and the surveys, 141 recruitment deviations (including 31 pre-model estimates), and 12 forecast recruitment deviations (Table \ref{tab:params}).

Fixed parameters in the model were as follows. Steepness was fixed at 0.80, the mean of the prior. A sensitivity analysis and a likelihood profile were performed for steepness. Natural mortality was fixed at 0.108 yr^-1^ for females, the median of the prior. Estimation of female natural mortality was explored during model development. The estimate of female natural mortality was low (around 0.082 yr^-1^) relative to the median of the prior which was based on maximum age; however, well within the prior distribution (SE = 0.438). There were limited observations of fish greater than 50 years of age, so a natural mortality that would be associated with a maximum around 65 years of age did not seem well supported. The 99th percentile of age data from West Coast surveys ranged between 45 - 50 years of age. Assumptions regarding `r spp` maximum age from other regions appear to have similar observations with a maximum age of 45 listed for British Columbia, Canada and the oldest age observed in the U.S. Gulf of Alaska of 59 years. Additionally, the population scale with female natural mortality estimated appeared low, where the catchability for the \gls{s-nwslope} and \gls{s-wcgbt} were above 2.0. The decision to fix natural mortality in the base model was based on each of these factors combined.  

The standard deviation of recruitment deviates was fixed at 0.35 ($\sigma_R$). Maturity-at-length was fixed as described above in Section \ref{maturation-and-fecundity}. Length-weight parameters were fixed at external estimates based on \gls{s-wcgbt} length-weight observations (Figure \ref{fig:est-len-wght}).

Sex-specific and dome-shaped selectivity was explored for all fleets within the model. Older `r spp`, particularly females, are often found in deeper waters and may move into areas that limit their availability to fishing gear. 
