## Base Model Results

The base model parameter estimates along with approximate asymptotic standard errors (SD column) are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in Table \ref{tab:referenceES}. Estimates of stock size over time are shown in Table \ref{tab:timeseries}. 

### Parameter Estimates

The male natural mortality parameter was estimated as a relative offset from the fixed female value within the model. Male natural mortality was estimated to be `r round(model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1", 3]*exp(model$parameters[model$parameters$Label == "NatM_p_1_Mal_GP_1", 3]),3)` yr^-1^ and the female natural mortality was fixed at `r round(model$parameters[model$parameters$Label == "NatM_p_1_Fem_GP_1", 3],3)` yr^-1^.  The female value was fixed at the median of the prior.  

The estimates of growth parameters by sex varied relative to the externally estimated starting values.  The length at age 1 and the maximum length estimates for both sexes was slightly less than the external estimates but were well within the 95 percent confidence interval given the estimated uncertainty (Table \ref{tab:params} and Figure \ref{fig:mod-est-len-age}). The estimated $k$ for female and male fish were greater than the values estimated externally using only available survey data (`r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3],3)` yr^-1^ for females and `r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3]*exp(model$parameters[model$parameters$Label == "VonBert_K_Mal_GP_1", 3]),3)` yr^-1^ for males).  The majority of growth for female and male `r spp` growth occurs at younger ages, reaching near maximum length by age 20-25, depending upon sex, with female `r spp` reaching  larger maximum lengths (Figure \ref{fig:mod-est-len-age}). 

Length-based selectivity curves were estimated for the fishery and survey fleets by sex.  The estimated selectivities are shown in Figure \ref{fig:selex}. The selectivity for both commercial fleets (California and Oregon/Washington) were parameterized using the double-normal selectivity where female selectivity was estimated as an offset from males. Dome-shape selectivity was explore for each of these fleets by sex during model development. The best fit to the California length data by sex was achieved with a asymptotic male selectivity and a dome-shaped selectivity for females with maximimum selection estimated less than 1.0.  The selectivity for the Oregon/Washington fleet was estimated to be dome-shaped for both sexes with maximum female selectivity less than 1.0. The selectivity for both commercial fleets shifted rightward or leftward by blocked year period, likely driven by management or fishery changes across time.

The selectivity of the \gls{s-tri} and the \gls{s-wcgbt} in the base model were estimated using the double-normal parameterization, allowing for dome-shaped selectivity. Female selectivity parameters were estimated as offsets from the male parameters. The \gls{s-tri} which surveyed depths 55 - 549 meters, only a subset of the depth range of `r spp`, had peak selectivity for both sexes around 30 cm and reduced selectivity for larger sizes where maximum female selectivity was less than 1.0. The \gls{s-wcgbt} which samples a wide range of depths (55 -1280 m) had the highest female selectivity across sizes but maximum selectivity was still less than 1.0.  The two slope survey, \gls{s-aslope} and \gls{s-nwslope}, that focused sampling at deeper depths were parameterized using a cubic spline function with allows for bi-modal selectivity peaks across size. 

Retention curves were assumed to be asymptotic. The estimated curves for each commercial fleet based on the historical time blocks and discarded length composition data are shown in Figure \ref{fig:retention}. The earliest retention curve for California, 1911-1947, was fixed left skewed for full retention since the input catches for this period included estimates of discard mortality.  The retention curves for both commercial fleets since the start of the ITQ fishery have shifted leftward indicating very limited discarding of `r spp`. 

The catchability for each of the surveys was analytically solved comparing observed to expected vulnerable biomass across all years.  The catchabiltiy for the \gls{s-tri} was `r round(exp(model$parameters[model$parameters$Label == "LnQ_base_Triennial(4)", 3]), 3)` and `r round(exp(model$parameters[model$parameters$Label == "LnQ_base_Triennial(4)", 3])*exp(model$parameters[model$parameters$Label == "LnQ_base_Triennial(4)_BLK4add_1995", 3]), 3)` for the early and late periods, respectively.  The catchability for the \gls{s-aslope} and the \gls{s-nwslope} was `r round(exp(model$parameters[model$parameters$Label == "Q_extraSD_AFSC_Slope(3)", 3]), 3)` and `r round(exp(model$parameters[model$parameters$Label == "Q_extraSD_NWFSC_Slope(5)", 3]), 3)` respectively. The \gls{s-wcgbt} catchability was `r round(exp(model$parameters[model$parameters$Label == "LnQ_base_NWFSC_WCGBT(6)", 3]), 3)`. 

Additional survey variability, process error added directly to each year's input standard deviation for the \gls{s-tri}, applied to both the early and late period of the survey, the \gls{s-aslope}, and the \gls{s-nwslope} was estimated within the model.  The model estimated a large added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_Triennial(4)", 3], 3)` for the \gls{s-tri}.
The added variance estimate for both of the slope surveys were similar at `r round(model$parameters[model$parameters$Label == "Q_extraSD_AFSC_Slope(3)", 3], 3)` and `r round(model$parameters[model$parameters$Label == "Q_extraSD_NWFSC_Slope(5)", 3], 3)`. No added variance was estimated for the \gls{s-wcgbt}.

The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}). Years with the highest recruitment deviations were estimated to have occurred in 2000 and 2009 with the lowest between 2003 - 2005. There is little information regarding recruitment prior to 1970 but are estimated in the base model to account for uncertainty around the unfished condition. Estimated recruitment deviations during years with the majority of the compositional data, after 1980, have relatively high uncertainty intervals indicating lack of support for clear strong or poor recruitment years across data sources. Recruitment deviations after 2015 are relatively uninformed with estimated deviations near zero where recruitment is estimated primarily based on the spawner-recruit curve (Figure \ref{fig:bh-curve}). The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adj}.

### Fits to the Data

There are numerous types of data for which the fits are discussed: survey abundance indices, discard data (rates, mean body weights, and length compositions), length composition data for the fisheries and surveys, marginal age compositions for the fisheries, and conditional age-at-length observations for the \gls{s-wcgbt} and \gls{s-nwslope}.

The fits to the survey indices are shown in Figures \ref{fig:wcgbt-index-fit} - \ref{fig:nwslope-index-fit}. The \gls{s-wcgbt} is the longest index of abundance for West Coast groundfish and was fit reasonably well for `r spp` with no estimated added variance (Figure \ref{fig:wcgbt-index-fit}). The index was variable with a slight dip around 2011 - 2013 but was relatively flat across years. The index of abundance for the \gls{s-tri} was fit as two periods, early 1980 - 1992 and late 1995 - 2004 using a shift in catchability. The year specific standard deviation estimated by VAST (thick black bars) was low compared to the large added variance (thin black lines) estimated within the model in order to fit each period of the index of abundance (Figure \ref{fig:tri-index-fit}). Even with the large estimated added variance the model did not fit the sharp peak in the 2004 estimate from the \gls{s-tri}. The indices from both slope surveys, \gls{s-aslope} and \gls{s-nwslope}, were generally flat and fit by the base model (Figures \ref{fig:afsc-index-fit} and \ref{fig:nwslope-index-fit}). For both surveys the estimated added variance allowed better fits to single year values from each of these surveys: \gls{s-aslope} 2001 estimate and and \gls{s-nwslope} values in 2000  and 2002. 

The observed WCGOP discard rates were fit by each fleet in the model using time blocks (Figures \ref{fig:ca-disc-fit} - \ref{fig:orwa-disc-fit}). The discard rates were fit well for California fleet based on the retention blocks in the model.  The fits to the discard rates for the Oregon/Washington fleet were more variable compared to the California fleet (Figure \ref{fig:orwa-disc-fit}). The estimated discard rate for the early block 1910 - 2001 were driven by fits to the Pikitch discard rates, which had low uncertainty in the annual discard rate, compared to the earlier discard rates which were more uncertain. Additionally, the Pikitch discard lengths were the sole source of discard size observations for this period.  The WCGOP data between 2002 - 2010 had equally split years of higher and lower discard rate observations with the model fitting the lower discard rates well due to the low uncertainty intervals on years with low discard rates (i.e., there were similar standard deviations across years but result in tighter intervals on lower discard rates). The fit to the mean weight of discarded `r spp` was good for both fishing fleets in the model (Figures \ref{fig:ca-disc-mbw-fit} and \ref{fig:orwa-disc-mbw-fit}).

The  WCGOP discard lengths by the California fleet were relatively well fit, expect for the most recent years where the observed lengths were quite variable (Figures \ref{fig:ca-disc-len-fit} and \ref{fig:ca-disc-pearson}). The period of variable lengths in recent years coincides with a decline in the number of observations by year.  The fits to the WCGOP discard lengths for the Oregon/Washington fleet fit well (Figures \ref{fig:orwa-disc-len-fit-1} - \ref{fig:orwa-disc-pearson}). The Pikitch discard lengths had little variability across size and the estimated model fit encapsulated the peak in the lengths but not the sharpness in observed discarding (1985 -1987 in Figure \ref{fig:orwa-disc-len-fit-1}).

Fits to the length data are shown based on the proportions of lengths observed by year and the Pearson residuals-at-length for all fleets. Detailed fits to the length data by year and fleet are provided in [Appendix A](#len-fit-data). Length composition aggregated fits by fleet are reasonably well fit and are shown in Figure \ref{fig:agg-fits}. The poorest fit was for unsexed length compositions from either the discard observations and the early year unsexed lengths from the Oregon/Washington fleet. There was little evidence for patterns of poor fits to the California length data Pearson residuals (Figure \ref{fig:ca-disc-pearson}). The Pearson residuals for the Oregon/Washington fleet were relatively small (maximum residual size = 1.66) similar to the California data but there was some evidence of the observations being greater than the predicted values (filled circles) for males around 36 cm (Figure \ref{fig:orwa-pearson}). The Oregon/Washington fleet had a high proportion of males observed at this size, greater than the proportion observed in the California fleet (Figure \ref{fig:agg-fits}). There was evidence of a slight female residual pattern around the largest sizes observed for Oregon/Washington, although the size of the residual was small. During model development increasing the selectivity of large female fish did not improve the fit to these data.  The mean length observed by year for both the California and Oregon/Washington fleet had larger mean lengths during the early years of available data (Figures \ref{fig:ca-mean-len} and \ref{fig:orwa-mean-len}). The mean of lengths observed in recent years by the California fleet ranged between 38 - 42 cm and ranged between 35-40 cm for the Oregon/Washington fleet.  

The observed ages aggregated across years for the California and Washington/Oregon fleet are shown in Figure \ref{fig:agg-age-fits}. The maximum size of the Pearson residuals for both fleets was generally small (maximum = 2.66, Figures \ref{fig:ca-pearson-age} and \ref{fig:orwa-pearson-age}). The mean age by year for California ranged between 12 - 18 years of age and the Oregon/Washington mean age was slightly lower ranging between 11 - 15 years of age (Figures \ref{fig:ca-mean-age} and \ref{fig:orwa-mean-age}). 
 
The length data from each survey were generally fit well (Figure \ref{fig:agg-fits}. The Pearson residuals for each survey show little evidence for model misfit to the data (Figures \ref{fig:tri-pearson} - \ref{fig:wcgbt-pearson}). The \gls{s-tri} observed the lowest mean length across years (less than 32 cm excluding 1980) and both slope surveys observed mean lengths ranging between 32 - 35.5 cm (Figures \ref{fig:tri-mean-len} - \ref{fig:nwslope-mean-len}). The mean length observed by the \gls{s-wcgbt} showed a slight pattern of increasing mean length between 2004 - 2012 and then a drop in mean length in 2013 which remained relatively constant around 33 - 34 cm for subsequent years (Figure \ref{fig:wcgbt-mean-len}).  

The ages from the \gls{s-nwslope} and \gls{s-wcgbt} were used as conditional-age-at-length data in the base model. The Pearson residuals by year for both data sets are available in the [Appendix]{#detailed-caal}. The fits to the conditional age-at-length data across ages and lengths each year are shown in Figures \ref{fig:nwslope-caal-fit-1} - \ref{fig:wcgbt-caal-fit-4} where the expected fit (blue line) general matches the observations except at the largest lengths where the number of observations by age, length, and year are limited. The observed mean age by year from the \gls{s-nwslope} was either above of below the model predicted mean age by year but within the confidence interval by year (Figure \ref{fig:nwslope-mean-caal}). The observed mean age and the model predictions were reasonably consistent until 2010for the \gls{s-wcgbt} (Figure \ref{fig:wcgbt-mean-age}). However, the recent years observed mean age (between 12 - 14 years of age) by year were greater compared to the model expected mean age (approximately 11.5 - 12 years of age).

### Population Trajectory

The predicted spawning biomass is given in Table \ref{tab:timeseries} and plotted in Figure \ref{fig:ssb}. The predicted spawning biomass time series shows a slow decline in spawning biomass from the 1950s through the mid-1990s as catches increased between 1940 and the late 1980s (Figure \ref{fig:catch}). The predicted spawning biomass begins to slowly increase around 2000 through the final model year `r endyr` likely driven by a decrease in removals over the last 25 years. The estimated total biomass follows the same general trend as observed in the spawning biomass (Figure \ref{fig:tot-bio}). The estimated spawning biomass relative to unfished equilibrium spawning biomass has remained relatively high, never dropping below 0.60, and well above the current management target of 0.25 (Figure \ref{fig:depl}). The relative biomass at the start of `r endyr +1` is estimated at `r round(model$derived_quants[model$derived_quants$Label == "Bratio_2021", "Value"],2)`.

Female `r spp` were never fully selected by either fishery or any survey since the largest females tend to move to deeper depths that extend beyond the maximum depth sampled. This behavior results in a subset of the spawning biomass that is unobserved and unavailable. The model predicted available and unavailable spawning biomass is shown in Figure \ref{fig:unavail-bio}. The estimates of the unavailable spawning biomass are based on the catch by fleet, the model estimated numbers-at-age, and the derived age-specific selectivity all by year. The estimated unavailable spawning biomass is shown broken out by small and large fish where small fish are defined as fish less than the age of derived peak selectivity. The sharp increase in small fish reflected in the upper right panel is primarily an artifact of the Oregon/Washington fleet beginning around this time, later than the California fleet, and then drops when selectivity and retention changes during the mid-1980s. There is a large portion of the female spawning biomass estimated to be unavailable relative to the available spawning biomass.

Recruitment deviations were estimated for the entire time series that was modeled (Figure \ref{fig:rec-devs} and discussed in Section \ref{parameter-estimates}). Recruitment deviations were estimated to be above average in the late 1990s, below average in the early 2000s, and then generally above average between 2008 - 2012.  The stock-recruit curve resulting from a value of steepness fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"],2)` is shown in Figure \ref{fig:sr-curve} with estimated recruitments also shown. The stock is predicted to have never fallen to low enough levels that the effects of steepness are obvious.  Steepness was not estimated in this model, but a likelihood profile across steepness values are shown in Section \ref{likelihood-profiles}.
