## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered by 5 percent. This was repeated 100 times with only 1 out of 100 runs returning to the base model likelihood. However, a better, lower negative log-likelihood, model fit was not found. In the jittering analysis models with similar log-likelihood values (difference < 0.50 units) were often found with little difference in overall model estimates indicating a relatively flat likelihood surface around the maximum likelihood estiamat. Through the jittering done as explained and likelihood profiles, we are confident that the base model as presented represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian.

### Sensitivity Analyses

Sensitivity analyses were conducted to examine the relative influence of specific changes to data inputs and model structural assumptions to further address uncertainty associated with the base model estimates and derived management quantities.  The majority of the sensitivity models are the result of a single change relative to base model (i.e., they are not the result of cumulative changes such as the modeling approach used with the bridging analysis). Comparisons of likelihood values and estimates of key parameters from the sensitivity analysis are shown in Tables \ref{tab:sensitivities1} and \ref{tab:sensitivities2}. Many additional sensitivity runs were explored during development and testing of the base model. This section focuses on the main data and structural sensitivity model runs and includes the following:

Data Sensitivities

\begin{enumerate}
   
  \item Remove the California commercial length data
  
  \item Remove the Oregon/Washington commercial length data
  
  \item Remove the AFSC slope survey length data
  
  \item Remove the Triennial survey length data
  
  \item Remove the NWFSC slope survey length data
  
  \item Remove the NWFSC WCGBT survey length data
  
  \item Remove the California commercial age data
  
  \item Remove the Oregon/Washington commercial age data
  
  \item Remove the NWFSC slope survey age data
  
  \item Remove the NWFSC WCGBT survey age data
  
  \item Remove the AFSC slope survey index
  
  \item Remove the Triennial survey index
  
  \item Remove the NWFSC slope survey index
  
  \item Remove the NWFSC WCGBT survey index
  
\end{enumerate}

Structural Sensitivities

\begin{enumerate}
   
  \item Estimate Lorenzen natural mortality ($M$) by sex with the change of $M$ occurring at approximately age-at-50-percent maturity of 10 years old;

  \item Allow the model to estimate sex-specific $M$ values;

  \item Fix $M$ values by sex at the estimates from the 2011 assessment of `r spp`;
  
  \item Fix $M$ values for each sex at the median of the prior distribution (0.108);
  
  \item Mirror the selectivity by sex and retention for the CA and OR/WA fishing fleets;

  \item Assume the 2011 parameterization of fishery selectivity;

  \item Assume the 2011 parameterization of survey selectivity;

  \item Fix the NWFSC Slope Survey female selectivity to asymptote at 1.0;

  \item Assume the 2011 length-at-maturity estimate;
  
  \item No estimation of recruitment deviations;
  
  \item Use of the McAllister and Ianelli method for data-weighting (Table \ref{tab:dw});
  
  \item Use of the Dirichlet Multinomial method for data-weighting (Table \ref{tab:dw}); and
  
  \item Fix the extra standard deviation parameters for the AFSC Slope, NWFSC Slope, and Triennial Surveys at a near negligible level (0.01).

\end{enumerate}

In general, the base model was the most sensitive (i.e., spawning biomass estimates beyond the 95 percent confidence interval for the base model) to models that applied alternative approaches to estimating or fixing natural mortality parameters and when the largest source of age data (\gls{s-wcgbt}) was removed. Fixing sex-specific $M$ at the 2011 assessment estimates (i.e., higher than the base model) resulted in an increase in overall spawning stock biomass and the fraction of unfished biomass (i.e., stock status), while adding the estimation of female $M$ or sex-specific Lorenzen $M$ (i.e., lower values than the base model) resulted in decreases relative to the base model (Table \ref{tab:sensitivities2}; Figures \ref{fig:sens-m-ssb} and \ref{fig:sens-m-relssb}). In general, natural mortality (fixed or estimated) ranged from 0.082 to 0.116 for females and 0.082 to 0.142 for males across sensitivity runs. The total negative log likelihood was slightly less for the models that estimated female $M$ and sex-specific Lorenzen $M$, suggesting a slightly better fit to the available data. However, natural mortality is often a difficult parameter to estimate in stock assessment such that model misspecification is always a concern. These two alternative $M$ models were not chosen as the base model for the following reasons. First, estimates near the lower range of $M$ values relate to a longevity of about 65 years (following from Hamel [-@hamel_method_2015]), which is not well supported by the observed data (i.e., few observations more than 50 years old). Second, the scale of the population was considerably reduced to the point where catchability doubled for the surveys, which for the \gls{s-wcgbt} and slope surveys meant unrealistically high (at or above 2) catchability coefficients. Third, the lack of contrast in data and in the population trajectory through time, as seen with `r spp`, are often limitations to estimating $M$ reliably without auxiliary information (e.g., tagging data), due to the inability of the model to decipher otherwise confounding causes of demographic change [@Wang1999; @Lee_est_m_2011].

The removal of ages from the \gls{s-wcgbt} (i.e., a considerable amount of the total available age data) resulted in lower estimates of spawning biomass and the fraction of unfished biomass compared to the inclusion of these data in the base model (Figures \ref{fig:sens-age-ssb} and \ref{fig:sens-age-relssb}). This result is not surprising given that these age data suggest a higher population scale (Figure \ref{fig:r0-profile}) compared to other sources of age information. Whereas the removal of the Oregon/Washington commercial age data had the opposite effect (increase spawning biomass), though not quite as large of an effect as the removal of the \gls{s-wcgbt} age data. The removal of other sources of age data led to largely insensitive results relative to the base model, as did the removal on any one source of length data (Figures \ref{fig:sens-length-ssb} and \ref{fig:sens-length-relssb}) or survey index (Figures \ref{fig:sens-index-ssb} and \ref{fig:sens-index-relssb}).  

Other changes in model structure that led to moderately sensitive results (i.e., divergent from, but within the 95 percent confidence interval of, the base model) include assumptions based upon selectivity (Figures \ref{fig:sens-select-ssb} and \ref{fig:sens-select-relssb}) and the method for weighting data (Figures \ref{fig:sens-biodata-ssb} and \ref{fig:sens-biodata-relssb}). While the McAllister and Ianneli approach to data weighting led to an 11 percent, on average, decline in spawning biomass across the time series compared to the base model, it had less of an impact on overall stock status (76 percent compared to 79 percent in 2021, respectively). In general, the Francis approach to data weighting that was used in the base model applied less weight relative to input sample sizes compared to the McAllister and Ianelli approach (Table \ref{tab:dw}). The Dirichlet multinomial approach to data weighting was abandoned due to inconsistent results relative to input sample sizes and parameters hitting bounds. Specifying survey selectivity patterns to match the form used in the 2011 assessment was the most sensitive among alternative selectivity scenarios examined in terms of overall stock size, and was also the most plausible of these in terms of the lowest total likelihood (Table \ref{tab:sensitivities2}), though not lower than the base model. This difference in stock size is largely explained by the increase in the male natural mortality estimate (Table \ref{tab:sensitivities2}).   

### Likelihood Profiles

Likelihood profiles were conducted for $R_0$, steepness, and sex-specific natural mortality values separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimated the remaining parameters based on the fixed parameter value.

In regards to values of log($R_0$), the negative log-likelihood was minimized at approximately log($R_0$) of `r round(log(model$derived_quants[model$derived_quants$Label == "Recr_Virgin",2]),2)`  (Figure \ref{fig:r0-profile}).  The estimate of log($R_0$) was informed by a relatively consistent signal from length data across fleets and survey. While the length data across sources supported log($R_0$) values around 12.0, the age data primarily informed by the \gls{s-wcgbt} supported higher values.  The stock scale was highly sensitive to values with the final stock status ranging between 0.60 to 1.0 (Figures \ref{fig:r0-ssb} and \ref{fig:r0-depl}.

For steepness, the negative log-likelihood supported values between 0.40 - 1.0 (Figure \ref{fig:r0-profile}).  Likelihood components by data source show that the  age data from the \gls{s-wcgbt} support a lower steepness values while the length data across most fleets in the model were relatively flat.  The surveys generally provide very little information concerning steepness but tend to support higher values of steepness. The estimated spawning biomass for `r spp` diverges most at the start of the timeseries (estimates of $SB0$) and across the final 25 years of the model (Figure \ref{fig:h-ssb})  The stock was estimated to be most depleted at the end of the time series with lower values of steepness (Figure \ref{fig:h-depl}).

The negative log-likelihood was minimized at a female natural mortality value 0.08 with values from 0.07 - 0.09 supported based on the total negative-log-likelihood (Figure \ref{fig:m-profile}). The profile was run under the base model assumption that the offset of male natural mortality was estimate based on the fixed female natural mortality.  The length data was generally uniformative across fleets and surveys except for the \gls{s-aslope} that supported lower natural mortality values. The age data from this \gls{s-wcgbt} supported lower female natural mortality values. The stock scale and status was highly variable across natural mortality values where lower values resulted in lower stock scale and status (Figures \ref{fig:m-ssb} and \ref{fig:m-depl}).

The negative log-likelihood was minimized at a male natural mortality offset value of 0.05 (a value of 0.114 yr^-1^ converted into regular space) with offset values from 0.0 - 0.1 supported based on the total negative-log-likelihood (Figure \ref{fig:m-male-profile}). The profile was run under the base model assumption that the female natural mortality was fixed at 0.108.  The length data generally supported offset values of -0.1 - 0.1. The age data from this \gls{s-wcgbt} supported higher male offset natural mortality values. The stock scale and status was highly variable across male natural mortality values where lower values resulted in lower stock scale and status (Figures \ref{fig:m-male-ssb} and \ref{fig:m-male-depl}). 

### Retrospective Analysis

A ten-year retrospective analysis was conducted by peeling off years of data ranging from 2010 - 2019 (i.e., "Data -1 Years" corresponds to data through 2019). The estimated spawning output was generally consistent with the base model when recent years of data were removed (Figures \ref{fig:retro-ssb}). Although, when the 9 and 10 years of data were removed (data availabel through 2010 and 2011) the estimate of stock scale dropped relative to the base model and other retrospective runs. The estimates of fraction unfished were fairly consistent with the base model (Figure \ref{fig:retro-depl}), except the retrospective run with 10 years of data removed estimated a slightly more depeleted stock relative to the base model trajectory.

### Historical Analysis

The estimated spawning output from previous assessments since 2001 are shown in Figure \ref{fig:past-assess}. The estimate of stock scale from the base model is considerably lower relative to the 2011 assessment estimate which was highly uncertain. The base model $SB_0$ was highly similar to the value estimated by the 2005 assessment, the stock trajectory from the base model diverged between 1960-2005 in comparison to the 2005 estimate. The relative stock status of the base model was relatively consistent in trend and scale with the estimate from the 2011 assessment, although slightly less optomistic but still well above the management target.  
