\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- *******************    Assessment Map      *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "map.png"), 
caption = "Map of the assessment area.",
label = 'map')
```	

<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "catch2 landings stacked.png"), 
caption = "Landings by fleet used in the base model",
label = 'catch')
```	

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	

<!-- ======================================================= -->
<!-- ***************   Discard Data  *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "discard_dataCA.png"), 
caption = "Observed discard rates for the California fleet",
label = 'ca-disc-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "discard_dataOR_WA.png"), 
caption = "Observed discard rates for the Oregon-Washington fleet",
label = 'orwa-disc-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bodywt_data_fltCA.png"), 
caption = "Observed discard mean weights for the California fleet",
label = 'ca-disc-wght-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bodywt_data_fltOR_WA.png"), 
caption = "Observed discard mean weights for the Oregon-Washington fleet",
label = 'orwa-disc-wght-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_flt1mkt1.png"), 
caption = "Observed discard lengths for the California fleet",
label = 'ca-disc-len-ob')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_flt2mkt1_page1.png"), 
caption = "Observed discard lengths for the Oregon-Washington fleet",
label = 'orwa-disc-len-ob')
```


<!-- ======================================================= -->
<!-- *************** Commercial Data *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Length_by_CA_port.png"), 
caption = "The number of length samples by port and year from California",
label = 'ca-len-port')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt1mkt2_page4.png"), 
caption = "Length composition data from the California commercial fleet",
label = 'ca-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_CA.png"), 
caption = "Mean length for California commercial fleet with 95 percent confidence intervals",
label = 'mean-ca-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat__aggregated_across_time.png"), 
caption = "Length composition data aggregated across years by fleet",
label = 'agg-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Age_by_CA_port.png"), 
caption = "The number of read otoliths samples by port and year from California",
label = 'ca-age-port')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agedat_bubflt1mkt2_page2.png"), 
caption = "Age composition data from the California commercial fleet",
label = 'ca-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agedat_data_weighting_TA1.8_CA.png"), 
caption = "Mean age for California commercial fleet with 95 percent confidence intervals",
label = 'mean-ca-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agedat__aggregated_across_time.png"), 
caption = "Age composition data aggregated across years by fleet",
label = 'agg-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Length_by_OR_port.png"), 
caption = "The number of length samples by port and year from Oregon",
label = 'or-len-port')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Length_by_WA_port.png"), 
caption = "The number of length samples by port and year from Washington",
label = 'wa-len-port')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt2mkt2_page3.png"), 
caption = "Length composition data from the Oregon-Washington commercial fleet",
label = 'orwa-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_OR_WA.png"), 
caption = "Mean length for Oregon-Washington commercial fleet with 95 percent confidence intervals",
label = 'mean-orwa-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Age_by_OR_port.png"), 
caption = "The number of read otoliths samples by port and year from Oregon",
label = 'or-age-port')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "commercial_comps", "plots", "Age_by_WA_port.png"), 
caption = "The number of read otoliths samples by port and year from Washington",
label = 'wa-age-port')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agedat_bubflt2mkt2_page2.png"), 
caption = "Age composition data from the Oregon-Washington commercial fleet",
label = 'orwa-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agedat_data_weighting_TA1.8_OR_WA.png"), 
caption = "Mean age for Oregon-Washington commercial fleet with 95 percent confidence intervals",
label = 'mean-orwa-age-data')
```

<!-- ======================================================= -->
<!-- ***************  NWFSC WCGBT Survey ******************* --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Length_by_Depth_by_Source.png"), 
caption = "Observed length by depth from each survey",
label = 'data-len-depth')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Age_by_Depth.png"), 
caption = "Observed age by depth from the NWFSC Slope and WCGBT surveys",
label = 'data-age-depth')
```

\newpage	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "plots", "Dover_sole_NWFSC_WCGBTS_CPUE_Depth_Latitude.png"), 
caption = "The catch-per-unit-effort (log-scale), lengths by sex observed by depth and latitude for the NWFSC WCGBT survey. The solid lines indicate the average length by depth or latitude by sex (red - females, blue - males, grey - unsexed)",
label = 'cpue-len')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "wcgbts", "plots", "WCGBTS_presence_by_depth_bin.png"), 
caption = "Observed proportion of positve tows and sex ratio by depth bins (m) from the NWFSC WCGBT survey",
label = 'pos-tows-sex-ratio')
```


\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "NWFSC.Combo_gamma", "QQ_Fn", "Posterior_Predictive-Histogram-1.jpg"), 
caption = "Q-Q and diagnostics for the NWFSC WCGBT survey",
label = 'wcgbt-qq')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "NWFSC.Combo_gamma", "quantile_residuals_on_map.png"), 
caption = "Residuals for the NWFSC WCGBT survey index",
label = 'wcgbt-resid')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "NWFSC.Combo_gamma", "VASTWestCoast_Index_2019.png"), 
caption = "The estimated index of abundance for the NWFSC WCGBT survey",
label = 'wcgbt-index')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "plots", "db_index_comparison.png"), 
caption = "VAST based indices compared to the design-based indices for each fleet",
label = 'db-vs-vast')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt6mkt0_page2.png"), 
caption = "Length composition data from the NWFSC WCGBT survey",
label = 'wcgbt-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_NWFSC_WCGBT.png"), 
caption = "Mean length for NWFSC WCGBT survey with 95 percent confidence intervals",
label = 'mean-wcgbt-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_gstagedat_bubflt6mkt0_page2.png"), 
caption = "Age composition data from the NWFSC WCGBT survey",
label = 'wcgbt-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALdat_data_weighting_TA1.8_condAgeNWFSC_WCGBT.png"), 
caption = "Mean age for NWFSC WCGBT survey with 95 percent confidence intervals",
label = 'mean-wcgbt-age-data')
```

\newpage

<!-- ======================================================= -->
<!-- ***************     Triennial   *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_early", "VASTWestCoast_Index_1992.png"), 
caption = "The estimated index of abundance for the early Triennial survey",
label = 'tri-early-index')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_late", "VASTWestCoast_Index_2004.png"), 
caption = "The estimated index of abundance for the late Triennial survey",
label = 'tri-late-index')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_early", "QQ_Fn", "Posterior_Predictive-Histogram-1.jpg"), 
caption = "Q-Q and diagnostics for the early Triennial survey (1980 - 1992)",
label = 'tri-early-qq')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_late", "QQ_Fn", "Posterior_Predictive-Histogram-1.jpg"), 
caption = "Q-Q and diagnostics for the late Triennial survey (1995 - 2004)",
label = 'tri-late-qq')
```	

\newpage	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_early", "quantile_residuals_on_map.png"), 
caption = "Residuals for the early Triennial survey",
label = 'tri-early-resid')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "dover_sole", "data", "Triennial_lognormal_late", "quantile_residuals_on_map.png"), 
caption = "Residuals for the late Triennial survey",
label = 'tri-late-resid')
```	

\newpage


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt4mkt0.png"), 
caption = "Length composition data from the Triennial survey",
label = 'tri-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_Triennial.png"), 
caption = "Mean length for Triennial with 95 percent confidence intervals",
label = 'mean-tri-len-data')
```

<!-- ======================================================= -->
<!-- ***************   AFSC Slope    *********************** --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "afsc_slope", "VASTWestCoast_Index_2001.png"), 
caption = "The estimated index of abundance for the AFSC Slope survey",
label = 'afsc-index')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "afsc_slope", "QQ_Fn", "Posterior_Predictive-Histogram-1.jpg"), 
caption = "Q-Q and diagnostics for the AFSC Slope survey ",
label = 'afsc-qq')
```

\newpage	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "afsc_slope", "quantile_residuals_on_map.png"), 
caption = "Residuals for the AFSC Slope survey",
label = 'afsc-resid')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt3mkt0.png"), 
caption = "Length composition data from the AFSC Slope survey",
label = 'afsc-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_AFSC_Slope.png"), 
caption = "Mean length for AFSC Slope survey with 95 percent confidence intervals",
label = 'mean-afsc-len-data')
```

<!-- ======================================================= -->
<!-- ***************   NWFSC Slope   *********************** --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "nwfsc_slope", "VASTWestCoast_Index_2002.png"), 
caption = "The estimated index of abundance for the NWFSC Slope survey",
label = 'nwfsc-index')
```	

\newpage

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "nwfsc_slope", "QQ_Fn", "Posterior_Predictive-Histogram-1.jpg"), 
caption = "Q-Q and diagnostics for the NWFSC Slope survey ",
label = 'nwfsc-qq')
```

\newpage	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey_indices", "nwfsc_slope", "QQ_Fn", "pearson_residuals_2.png"), 
caption = "Residuals for the NWFSC Slope survey",
label = 'nwfsc-resid')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_bubflt5mkt0.png"), 
caption = "Length composition data from the NWFSC Slope survey",
label = 'nw-slope-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lendat_data_weighting_TA1.8_NWFSC_Slope.png"), 
caption = "Mean length for NWFSC Slope survey with 95 percent confidence intervals",
label = 'mean-nw-slope-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_gstagedat_bubflt5mkt0.png"), 
caption = "Age composition data from the NWFSC Slope survey",
label = 'nw-slope-age-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALdat_data_weighting_TA1.8_condAgeNWFSC_Slope.png"), 
caption = "Mean age for NWFSC Slope survey with 95 percent confidence intervals",
label = 'mean-nw-slope-age-data')
```

<!-- ======================================================= -->  
<!-- ******************   Biology  ************************* --> 
<!-- ======================================================= -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Maturity_Comparison.png"), 
caption = "Comparison of the maturity-at-length assumed in the 2011 assessment and the new estimate used in the base model",
label = 'compare-mat-at-len')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Maturity_by_Area.png"), 
caption = "Comparison of the maturity-at-length between fish sample north and south of Point Reyes",
label = 'spat-mat-at-len')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Maturity_Samples_by_Area.png"), 
caption = "Comparison of the observed sizes and ages by depth between fish sample north and south of Point Reyes",
label = 'samples-north-south')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Len_Age_by_Latitude.png"), 
caption = "Comparison of the observed sizes and ages by latitude where the vertical black dashed line at Point Reyes",
label = 'fish-by-lat')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Length_Weight_2020.png"), 
caption = "Externally estimated length-weight by sex",
label = 'est-len-wght')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Length_Age_by_Sex_2020.png"), 
caption = "Externally estimated length-at-age by sex",
label = 'est-len-at-age')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Length_Age_by_Area_1panel.png"), 
caption = "Externally estimated length-at-age by sex for four regions off the West Coast",
label = 'est-len-at-age-region')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "LengthAgeData_heatmap.png"), 
caption = "Temporal patterns in mean length-at-age (cm) data. Colors correspond to different length-at-age values as shown in the legend, with red being the smallest fish (across all years and ages) and blue being the largest fish",
label = 'tv-len-at-age')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "WeightAgeData_heatmap.png"), 
caption = "Temporal patterns in mean weight-at-age (kg) data. Colors correspond to different weight-at-age values as shown in the legend, with red being the lightest fish (across all years and ages) and blue being the heaviest fish",
label = 'tv-wght-at-age')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "survey", "wcgbts", "plots","2011_strata", "NWFSC WCGBTS_length_fraction_female.png"), 
caption = "Fraction female by length observed by the NWFSC WCGBT survey",
label = 'sex-by-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "Frac_Female_Lat_Depth.png"), 
caption = "Fraction female observations by depth and latitude from the NWFSC WCGBT survey",
label = 'fem-by-lat-depth')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(data_loc, "biology", "plots", "PacFIN_Age_Method.png"), 
caption = "Comparison between break-and-burn versus scale age reads",
label = 'scale-age')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "numbers5_ageerrorSD.png"), 
caption = "The standard deviation by age for two ageing error applied to age data in the base model (method 1: CAP Lab, method 2: CDFW)",
label = 'age-error')
```	



<!-- ======================================================= -->  
<!-- ******************   Bridge   ************************* --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "model_bridge_compare2_spawnbio_uncertainty.png"),
caption = "Model version bridge comparison of estimated spawning biomass",
label = 'bridge-ssb')
```

```{r, results = 'asis'}

add_figure(
filein = file.path(brid_loc, "_plots", "model_bridge_compare4_Bratio_uncertainty.png"),
caption = "Model version bridge comparison of estimated fraction unfished",
label = 'bridge-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "data_2010_bridge_compare2_spawnbio_uncertainty.png"),
caption = "Data updated through 2010 bridge comparison of estimated spawning biomass",
label = 'data-bridge-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "data_2010_bridge_compare4_Bratio_uncertainty.png"),
caption = "Data updated through 2010 bridge comparison of estimated fraction unfished",
label = 'data-bridge-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "1.9_all_data_2020_compare2_spawnbio_uncertainty.png"),
caption = "All data updated through 2020 bridge comparison of estimated spawning biomass",
label = 'all-data-bridge-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "1.9_all_data_2020_compare4_Bratio_uncertainty.png"),
caption = "All data updated through 2020 bridge comparison of estimated fraction unfished",
label = 'all-data-bridge-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "2.0_offset_selex_bridge_compare2_spawnbio_uncertainty.png"),
caption = "Estimated spawning biomass based on select structural changes and parameter updates",
label = 'structure-bridge-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(brid_loc, "_plots", "2.0_offset_selex_bridge_compare4_Bratio_uncertainty.png"),
caption = "Estimated fraction of unfished based on select structural changes and parameter updates",
label = 'structure-bridge-depl')
```


<!-- ====================================================================== -->
<!-- *********************    Priors            ********************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "h_prior.png"),
caption = "Prior distribution for steepness",
label = 'h-prior')
```

<!-- ====================================================================== -->
<!-- *********************  Model Est. Biology       ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"),
caption = "Model estimated length-at-age in the bginning of the year. Shaded area indicates 95 percent distribution of length-at-age around the estimaed growth curve",
label = 'mod-est-len-age')
```

<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "selectivity.png"),
caption = "Selectivity by fleet",
label = 'selex')
```

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "dover_retention.png"),
caption = "Estimated retention curves by time block",
label = 'retention')
```


<!-- ======================================================= -->  
<!-- ****************** Recruitment ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "recruit_fit_bias_adjust.png"),
caption = "Recruitment bias adjustment applied in the base model",
label = 'bias-adj')
```

<!-- ====================================================================== -->
<!-- ****************** Fit to the Index Data  **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_NWFSC_WCGBT"), 
caption = "Fit to the NWFSC WCGBTS index of abundance",
label = 'wcgbt-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_Triennial"), 
caption = "Fit to the Triennial survey index of abundance. Thicker lines indicate input uncertainty before the addition of estimated additional uncertainty parameter",
label = 'tri-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_AFSC_Slope"), 
caption = "Fit to the AFSC Slope survey index of abundance. Thicker lines indicate input uncertainty before the addition of estimated additional uncertainty parameter",
label = 'afsc-index-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "index2_cpuefit_NWFSC_Slope"), 
caption = "Fit to the NWFSC Slope survey index of abundance. Thicker lines indicate input uncertainty before the addition of estimated additional uncertainty parameter",
label = 'nwslope-index-fit')
```



<!-- ====================================================================== -->
<!-- ****************** Fit to the Discard Data *************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "discard_fitCA.png"), 
caption = "Fit to the annual discard rates for the California fleet",
label = 'ca-disc-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "discard_fitOR_WA.png"), 
caption = "Fit to the annual discard rates for the Oregon/Washington fleet",
label = 'orwa-disc-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bodywt_fit_fltCA.png"), 
caption = "Fit to the annual mean body weight observations for the California fleet",
label = 'ca-disc-mbw-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bodywt_fit_fltOR_WA.png"), 
caption = "Fit to the annual mean body weight observations for the Oregon/Washington fleet",
label = 'orwa-disc-mbw-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_flt1mkt1.png"), 
caption = "Fit to the annual length composition of discarded fish for the California fleet",
label = 'ca-disc-len-fit')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt1.png"), 
caption = "Pearson residuals to annual length composition of discarded fish for the California fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'ca-disc-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_flt2mkt1_page1.png"), 
caption = "Fit to the annual length composition of discarded fish for the Oregon/Washington fleet",
label = 'orwa-disc-len-fit-1')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_flt2mkt1_page2.png"), 
caption = "Fit to the annual length composition of discarded fish for the Oregon/Washington fleet",
label = 'orwa-disc-len-fit-2')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt1_page2.png"), 
caption = "Pearson residuals to annual length composition of discarded fish for the Oregon/Washington fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'orwa-disc-pearson')
```

<!-- ====================================================================== -->
<!-- ****************** Fit to the Composition Data **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit__aggregated_across_time.png"), 
caption = "Aggregated length composition fit across time by fleet",
label = 'agg-fits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt1mkt2_page4.png"), 
caption = "Pearson residuals to annual length composition for the California fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'ca-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt2mkt2_page3.png"), 
caption = "Pearson residuals to annual length composition for the Oregon/Washington fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'orwa-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_CA.png"), 
caption = "Mean length observations for the California fleet",
label = 'ca-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_OR_WA.png"), 
caption = "Mean length observations for the Oregon/Washington fleet",
label = 'orwa-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agefit__aggregated_across_time.png"), 
caption = "Aggregated age composition fit across time by fleet",
label = 'agg-age-fits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agefit_residsflt1mkt2_page2.png"), 
caption = "Pearson residuals to annual age composition for the California fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'ca-pearson-age')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agefit_residsflt2mkt2_page2.png"), 
caption = "Pearson residuals to annual age composition for the Oregon/Washington fleet. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'orwa-pearson-age')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agefit_data_weighting_TA1.8_CA.png"), 
caption = "Mean age observations for the California fleet",
label = 'ca-mean-age')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_agefit_data_weighting_TA1.8_OR_WA.png"), 
caption = "Mean age observations for the Oregon/Washington fleet",
label = 'orwa-mean-age')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt4mkt0.png"), 
caption = "Pearson residuals to annual length composition for the Triennial survey. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'tri-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt3mkt0.png"), 
caption = "Pearson residuals to annual length composition for the AFSC Slope survey. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'afsc-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt5mkt0.png"), 
caption = "Pearson residuals to annual length composition for the NWFSC Slope survey. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'nwslope-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_residsflt6mkt0_page2.png"), 
caption = "Pearson residuals to annual length composition for the NWFSC WCGBTS. Closed bubbles are positive residuals (observed > expected) and open bubbles are negative residuals (observed < expected)",
label = 'wcgbt-pearson')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_Triennial.png"), 
caption = "Mean length observations for the Triennial",
label = 'tri-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_AFSC_Slope.png"), 
caption = "Mean length observations for the AFSC Slope survey",
label = 'afsc-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_NWFSC_Slope.png"), 
caption = "Mean length observations for the NWFSC Slope survey",
label = 'nwslope-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_lenfit_data_weighting_TA1.8_NWFSC_WCGBT.png"), 
caption = "Mean length observations for the NWFSC WCGBTS",
label = 'wcgbt-mean-len')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt5mkt0_page1.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC Slope survey (plot 1 of 2) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'nwslope-caal-fit-1')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt5mkt0_page2.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC Slope survey (plot 2 of 2) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'nwslope-caal-fit-2')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page1.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 1 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-1')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page2.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 2 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-2')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page3.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 3 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-3')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page4.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 4 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-4')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page5.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 5 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-5')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_Andre_plotsflt6mkt0_page6.png"), 
caption = "Conditional age-at-length for mean age and standard deviation for the NWFSC WCGBT (plot 6 of 6) Left plots are mean conditional age-at-length by size-class (observed and predicted) with 90 percent confidence intervals based on adding 1.64 standard error  of mean to the data. Right plots in each pair are standard error of mean age-at-length (observed and predicted) with 90 percent confidence intervalss based on the chi-square distribution",
label = 'wcgbt-caal-fit-6')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeNWFSC_Slope.png"), 
caption = "Mean age from conditional age-at-length data for the NWFSC Slope survey",
label = 'nwslope-mean-caal')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "comp_condAALfit_data_weighting_TA1.8_condAgeNWFSC_WCGBT.png"), 
caption = "Mean age observations from the conditional age-at-length data from the NWFSC WCGBTS",
label = 'wcgbt-mean-age')
```


<!-- ======================================================= -->  
<!-- ****************** Time Series ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts7_Spawning_biomass_(mt)_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning biomass",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "ts9_Fraction_of_unfished_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning biomass",
label = 'depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "unavailable_biomass.png"),
caption = "Proportion of biomass unavailable due to selectivity for small and large fish.",
label = 'unavail-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SR_curve.png"), 
caption = "Stock recruit curve where point color indicate year, with warmer colors (yellow to green) indicating earlier years and cooler colors (blue) showing later years",
label = 'sr-curve')
```


<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estiamted correlations between the biomass ratio and SPR ratio.",
label = 'phase')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivities and with steepness fixed at 0.80",
label = 'yield')
```


<!-- ======================================================= -->  
<!-- ****************** Sensitivities ********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_1_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models that remove (-) sources of length data",
label = 'sens-length-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_1_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models that remove (-) sources of length data",
label = 'sens-length-relssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_2_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models that remove (-) sources of age data",
label = 'sens-age-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_2_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models that remove (-) sources of age data",
label = 'sens-age-relssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_3_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models that remove (-) sources of index data",
label = 'sens-index-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_3_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models that remove (-) sources of index data",
label = 'sens-index-relssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_4_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models to natural mortality including estimating females, estimating an age-specific Lorenzen relationship for males and females, fixing male and female parameters at the median of the prior, and fixing natural mortality at estimates
from the 2011 assessment",
label = 'sens-m-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_4_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models to natural mortality including estimating females, estimating an age-specific Lorenzen relationship for males and females, fixing male and female parameters at the median of the prior, and fixing natural mortality at estimates
from the 2011 assessment",
label = 'sens-m-relssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "SurveyQ_vs_M.png"),
caption = "Survey catchability estimates for the base model and alternative natural mortality sensitivity runs",
label = 'sens-m-survQ')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_5_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models to selectivity including the parameterization of fishery selectivity following the 2011 assessment, the parameterization of survey selectivity following the 2011 assessment, mirroring California  and Oregon/Washing commercial selectivity, and forcing one index (the NWFSC slope survey) to be asymptotic",
label = 'sens-select-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_5_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models to selectivity including the parameterization of fishery selectivity following the 2011 assessment, the parameterization of survey selectivity following the 2011 assessment, mirroring California  and Oregon/Washing commercial selectivity, and forcing one index (the NWFSC slope survey) to be asymptotic",
label = 'sens-select-relssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_6_compare2_spawnbio_uncertainty.png"),
caption = "Estimates of spawning biomass for the base model and alternative sensitivity models including using the maturity ogive from the 2011 assessment, estimating no recruitment deviations, effectively not allowing extra survey variance (standard deviation), and applying the McAllistar and Ianelli approach to data weighting",
label = 'sens-biodata-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(sens_loc, "_plots", "7.0.1_base_6_compare4_Bratio_uncertainty.png"),
caption = "Estimates of relative spawning biomass for the base model and alternative sensitivity models including using the maturity ogive from the 2011 assessment, estimating no recruitment deviations, effectively not allowing extra survey variance (standard deviation), and applying the McAllistar and Ianelli approach to data weighting",
label = 'sens-biodata-relssb')
```

<!-- ======================================================= -->  
<!-- ******************  Likelihoods  ********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "piner_panel_SR_LN(R0).png"), 
caption = "Change in the negative log-likelihood across a range of log(R0) values",
label = 'r0-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning biomass across a range of log(R0) values",
label = 'r0-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_LN(R0)"),  "SR_LN(R0)_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of log(R0) values",
label = 'r0-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "piner_panel_SR_BH_steep.png"), 
caption = "Change in the negative log-likelihood across a range of steepness values",
label = 'h-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning biomass across a range of steepness values",
label = 'h-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_SR_BH_steep"),  "SR_BH_steep_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of steepness values",
label = 'h-depl')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "piner_panel_NatM_p_1_Fem_GP_1.png"), 
caption = "Change in the negative log-likelihood across a range of female natural mortality values",
label = 'm-profile')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare1_spawnbio.png"), 
caption = "Change in the estimate of spawning biomass across a range of female natural mortality values",
label = 'm-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_profile_NatM_p_1_Fem_GP_1"),  "NatM_p_1_Fem_GP_1_trajectories_compare3_Bratio.png"), 
caption = "Change in the estimate of fraction unfished across a range of female natural values",
label = 'm-depl')
```

<!-- ======================================================= -->  
<!-- ****************** Retrospective ********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_retro"),  "compare2_spawnbio_uncertainty.png"), 
caption = "Change in the estimate of spawning biomass when the most recent 10 years of data area removed sequentially",
label = 'retro-ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(paste0(mod_loc, "_retro"),  "compare4_Bratio_uncertainty.png"),
caption = "Change in the estimate of fraction unfished when the most recent 10 years of data area removed sequentially",
label = 'retro-depl')
```

<!-- ======================================================= -->  
<!-- ************* Compare w/ 2011 & 2005 ****************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path("figs", "assessment_history.png"), 
caption = "Estimates of spawning output (also referred to as spawning biomass) across the base model and previous assessments of Dover sole",
label = 'past-assess')
```