\clearpage

# Appendix A

## Detailed Fit to Length Composition Data 

```{r, results='asis'}
#plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
#len_fit = plot_info[which(plot_info$category == "LenComp"), ]
#plot.vec = grep("comp_lenfit_flt", len_fit$label)
#filein = file.path(mod_loc, "plots")
#
#for (a in plot.vec){
#	cap = len_fit$caption[a]
#	lab = len_fit$label[a]
#	add_figure(filein = file.path(filein, len_fit$file[a]), 
#			   caption = "", 
#			   label = lab)
#}

```

\clearpage

## Detailed Fit to Age Composition Data 


```{r, results='asis'}
#plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
#len_fit = plot_info[which(plot_info$category == "AgeComp"), ]
#plot.vec = grep("comp_agefit_flt", len_fit$label)
#filein = file.path(mod_loc, "plots")
#
#for (a in plot.vec){
#	cap = len_fit$caption[a]
#	lab = len_fit$label[a]
#	add_figure(filein = file.path(filein, len_fit$file[a]), 
#			   caption = cap, 
#			   label = lab)
#}

```

\clearpage

## Detailed Fit to Conditional-Age-at-Length Composition Data 


```{r, results='asis'}
#plot_info = read.csv(file.path(mod_loc, "plots", "plotinfotable_for_doc.csv"))
#len_fit = plot_info[which(plot_info$category == "A@LComp"), ]
#plot.vec = grep("comp_condAALfit_resids", len_fit$label)
#filein = file.path(mod_loc, "plots")

#for (a in plot.vec){
#	cap = len_fit$caption[a]
#	lab = len_fit$label[a]
#	add_figure(filein = file.path(filein, len_fit$file[a]), 
#			   caption = , 
#			   label = lab)
#}

#plot.vec = grep("comp_condAALfit_Andre", len_fit$label)
#filein = file.path(mod_loc, "plots")

#for (a in plot.vec){
#	cap = len_fit$caption[a]
#	lab = len_fit$label[a]
#	add_figure(filein = file.path(filein, len_fit$file[a]), 
#			   caption = "Conditional AAL plot, whole catch, NWFSC WCGBT survey. These plots show mean age and std. dev. in conditional age-at-length. Left plots are mean age-at-length by size-class (obs. and pred.) with 90 percent CIs based on adding 1.64 SE of mean to the data. Right plots in each pair are SE of mean age-at-length (obs. and pred.) with 90 percent CIs based on the chi-square distribution", 
#			   label = lab)
#}

```